### ISSUE TITLE
No support for deno.json imports

### ISSUE THREAD

**Issue by reggi** [denoland/fresh#1001]
Fresh doesn't yet support 1.3.0 feature ["deno.json becomes an import map"](https://deno.com/blog/v1.30#denojson-becomes-an-import-map). 

```bash
➜  hello-fresh deno task start
Task start deno run -A --watch=static/,routes/ dev.ts
Watcher Process started.
The manifest has been generated for 3 routes and 1 islands.
error: Uncaught (in promise) Error: deno.json must contain an 'importMap' property.
      throw new Error("deno.json must contain an 'importMap' property.");
            ^
    at Function.fromManifest (https://deno.land/x/fresh@1.1.2/src/server/context.ts:111:13)
    at start (https://deno.land/x/fresh@1.1.2/src/server/mod.ts:64:35)
    at file:///Users/thomasreggi/Desktop/hello-fresh/main.ts:13:7
Watcher Process finished. Restarting on file change...
```

**Comment by jollytoad** [comment]
Until Fresh adds support for this, you can use a work-around of passing the deno.json as the import map, in your `main.ts`...

```
import manifest from "./fresh.gen.ts";

await start({
  ...manifest,
  config: {
    ...manifest.config,
    importMap: './deno.json'
  }
});
```

**Comment by tunnckoCore** [comment]
GOLD!

Thanks.
