### ISSUE TITLE
ERROR: Do not know how to load path: deno:npm:zustand@4.3.6

### ISSUE THREAD

**Issue by JacobWeisenburger** [denoland/fresh#1091]
Anyone know how to fix this error?

```
An error occurred during route handling or page rendering. Error: Build failed with 1 error:
deno:file:///C:/_Software/project/lib/makeStore.ts:1:38: ERROR: Do not know how to load path: deno:npm:zustand@4.3.6
    at failureErrorWithLog (https://deno.land/x/esbuild@v0.14.51/mod.js:1601:15)
    at https://deno.land/x/esbuild@v0.14.51/mod.js:1243:28
    at runOnEndCallbacks (https://deno.land/x/esbuild@v0.14.51/mod.js:1023:63)
    at buildResponseToResult (https://deno.land/x/esbuild@v0.14.51/mod.js:1241:7)
    at https://deno.land/x/esbuild@v0.14.51/mod.js:1354:14
    at https://deno.land/x/esbuild@v0.14.51/mod.js:655:9
    at handleIncomingPacket (https://deno.land/x/esbuild@v0.14.51/mod.js:752:9)
    at readFromStdout (https://deno.land/x/esbuild@v0.14.51/mod.js:621:7)
    at https://deno.land/x/esbuild@v0.14.51/mod.js:1880:11
```

```ts
// import_map.json
{
    "imports": {
        "zustand": "npm:zustand@4.3.6",
        "$fresh/": "https://deno.land/x/fresh@1.1.4/"
    }
}
```

```
$ deno --version
deno 1.32.1 (release, x86_64-pc-windows-msvc)
v8 11.2.214.9
typescript 5.0.2
```

**Comment by hashrock** [comment]
npm specifier is not supported in fresh for now. see:

https://github.com/denoland/fresh/issues/978

**Comment by JacobWeisenburger** [comment]
😢
