### ISSUE TITLE
twindv1 plugin error: Uncaught ReferenceError: MutationObserver is not defined

### ISSUE THREAD

**Issue by radicand** [denoland/fresh#1110]
I'm attempting to add the twindv1 plugin to my Fresh project, and am getting an error seemingly related to `@twind/core`, but initialized via the `twindv1` plugin. I'm at a loss for how to move past this. I'm using Fresh v1.1.5 with Deno 1.32.3.

```
Task dev deno run -A --watch=static/,routes/,import_map.json dev.ts
Watcher Process started.
The manifest has been generated for 16 routes and 4 islands.
error: Uncaught ReferenceError: MutationObserver is not defined
    at rt (https://esm.sh/v114/@twind/core@1.1.3/deno/core.mjs:2:14902)
    at nt (https://esm.sh/v114/@twind/core@1.1.3/deno/core.mjs:2:15368)
    at ft (https://esm.sh/v114/@twind/core@1.1.3/deno/core.mjs:2:17583)
    at setup (https://deno.land/x/fresh@1.1.5/plugins/twindv1/shared.ts:26:3)
    at twindv1 (https://deno.land/x/fresh@1.1.5/plugins/twindv1.ts:9:3)
```

```
❯ deno --version
deno 1.32.3 (release, aarch64-apple-darwin)
v8 11.2.214.9
typescript 5.0.3
```

**Comment by huai-jie** [comment]
try deno upgrade --version 1.32.1

**Comment by huai-jie** [comment]
you could refer to this https://github.com/denoland/fresh/issues/1103#issuecomment-1498416118

**Comment by radicand** [comment]
@huai-jie thanks for this; however it does not have any effect on this case though.

```
❯ deno upgrade --version 1.32.1
Downloading https://github.com/denoland/deno/releases/download/v1.32.1/deno-aarch64-apple-darwin.zip
Deno is upgrading to version 1.32.1
Archive:  /var/folders/_1/rg0z88jn5_3cmly9shy0rjk00000gn/T/.tmp7LFMEx/deno.zip
  inflating: deno                    
Upgraded successfully
❯ deno task start
Task start deno run -A main.ts
error: Uncaught ReferenceError: MutationObserver is not defined
    at rt (https://esm.sh/v114/@twind/core@1.1.3/deno/core.mjs:2:14902)
    at nt (https://esm.sh/v114/@twind/core@1.1.3/deno/core.mjs:2:15368)
    at ft (https://esm.sh/v114/@twind/core@1.1.3/deno/core.mjs:2:17583)
    at setup (https://deno.land/x/fresh@1.1.5/plugins/twindv1/shared.ts:26:3)
    at twindv1 (https://deno.land/x/fresh@1.1.5/plugins/twindv1.ts:9:3)
❯ deno upgrade
Looking up latest version
Found latest version 1.32.3
Downloading https://github.com/denoland/deno/releases/download/v1.32.3/deno-aarch64-apple-darwin.zip
Deno is upgrading to version 1.32.3
Archive:  /var/folders/_1/rg0z88jn5_3cmly9shy0rjk00000gn/T/.tmpR0NRmN/deno.zip
  inflating: deno                    
Upgraded successfully
❯ deno task start
Task start deno run -A main.ts
error: Uncaught ReferenceError: MutationObserver is not defined
    at rt (https://esm.sh/v114/@twind/core@1.1.3/deno/core.mjs:2:14902)
    at nt (https://esm.sh/v114/@twind/core@1.1.3/deno/core.mjs:2:15368)
    at ft (https://esm.sh/v114/@twind/core@1.1.3/deno/core.mjs:2:17583)
    at setup (https://deno.land/x/fresh@1.1.5/plugins/twindv1/shared.ts:26:3)
    at twindv1 (https://deno.land/x/fresh@1.1.5/plugins/twindv1.ts:9:3)
```

**Comment by hashrock** [comment]
How about executing this: 

> deno run -Ar main.ts

**Comment by radicand** [comment]
Still the same:
```
❯ deno run -Ar main.ts
error: Uncaught ReferenceError: MutationObserver is not defined
    at rt (https://esm.sh/v114/@twind/core@1.1.3/deno/core.mjs:2:14902)
    at nt (https://esm.sh/v114/@twind/core@1.1.3/deno/core.mjs:2:15368)
    at ft (https://esm.sh/v114/@twind/core@1.1.3/deno/core.mjs:2:17583)
    at setup (https://deno.land/x/fresh@1.1.5/plugins/twindv1/shared.ts:26:3)
    at twindv1 (https://deno.land/x/fresh@1.1.5/plugins/twindv1.ts:9:3)
```

**Comment by radicand** [comment]
A "fresh" project did not exhibit the issue, so after careful step-tracing, it was determined that the side-by-side inclusion of our `*.test.tsx` files were the cause. After moving the test files out of the route tree, all is well.
