### ISSUE TITLE
error when running www

### ISSUE THREAD

**Issue by deer** [denoland/fresh#1266]
When I try to do `deno task start` from `www`, I get the following error:
```
An error occurred during route handling or page rendering. Error: Component's "onClick" property should be a function, but got [string] instead
<button type="button" class="bg-gray-200 font-bold text-gray-400 rounded-full py-1 px-2 w-full mb-2" onClick="document.querySelector(\".DocSearch.DocSearch-Button\").click()" />

  in button
  in DocsSidebar
  in MobileSidebar
  in Main
  in DocsPage
  in Component
  in default

    at i.__b (https://esm.sh/stable/preact@10.15.1/denonext/debug.js:35:139)
    at k (https://esm.sh/v125/preact-render-to-string@6.1.0/X-ZS8q/denonext/preact-render-to-string.mjs:2:2086)
    at k (https://esm.sh/v125/preact-render-to-string@6.1.0/X-ZS8q/denonext/preact-render-to-string.mjs:2:2018)
    at k (https://esm.sh/v125/preact-render-to-string@6.1.0/X-ZS8q/denonext/preact-render-to-string.mjs:2:2591)
    at k (https://esm.sh/v125/preact-render-to-string@6.1.0/X-ZS8q/denonext/preact-render-to-string.mjs:2:3649)
    at k (https://esm.sh/v125/preact-render-to-string@6.1.0/X-ZS8q/denonext/preact-render-to-string.mjs:2:2018)
    at k (https://esm.sh/v125/preact-render-to-string@6.1.0/X-ZS8q/denonext/preact-render-to-string.mjs:2:3649)
    at k (https://esm.sh/v125/preact-render-to-string@6.1.0/X-ZS8q/denonext/preact-render-to-string.mjs:2:2018)
    at k (https://esm.sh/v125/preact-render-to-string@6.1.0/X-ZS8q/denonext/preact-render-to-string.mjs:2:3649)
    at k (https://esm.sh/v125/preact-render-to-string@6.1.0/X-ZS8q/denonext/preact-render-to-string.mjs:2:2018)
```
Am I doing something wrong?

**Comment by deer** [comment]
It seems to work with `273aa2a` from https://github.com/denoland/fresh/pull/1019, but when I do `git checkout be08573` from https://github.com/denoland/fresh/pull/1256 it start showing the above. @marvinhagemeister , is this expected?

**Comment by marvinhagemeister** [comment]
Oh no that's a tricky one. On one hand React folks expect that to throw. I haven't seen an inline string as a click handler in forever. Can reproduce it on my end.
