### ISSUE TITLE
Auto updater when changing source directory does not work

### ISSUE THREAD

**Issue by foenyx-dev** [denoland/fresh#1338]
Hi :D,

I tried to update deno fresh w/ command `deno task update` after changing source directory to src/ following [doc](https://fresh.deno.dev/docs/examples/changing-the-src-dir), it does not work.

```bash
PS C:\<redacted_path>\fresh> deno task update
Task update deno run -A -r https://fresh.deno.dev/update .
error: Uncaught (in promise) WalkError: Le chemin d’accès spécifié est introuvable. (os error 3): readdir 'C:\<redacted_path>\fresh\routes' for path "C:\<redacted_path>\fresh\routes"
  return new WalkError(err, root);
         ^
    at wrapErrorWithPath (https://deno.land/std@0.190.0/fs/walk.ts:48:10)
    at walk (https://deno.land/std@0.190.0/fs/walk.ts:134:11)
    at eventLoopTick (ext:core/01_core.js:183:11)
    at async collectDir (https://deno.land/x/fresh@1.2.0/src/dev/mod.ts:31:20)
    at async Promise.all (index 0)
    at async collect (https://deno.land/x/fresh@1.2.0/src/dev/mod.ts:47:29)
    at async https://deno.land/x/fresh@1.2.0/update.ts:188:18
Caused by: NotFound: Le chemin d’accès spécifié est introuvable. (os error 3): readdir 'C:\<redacted_path>\fresh\routes'
    at async Object.[Symbol.asyncIterator] (ext:deno_fs/30_fs.js:163:19)
    at async walk (https://deno.land/std@0.190.0/fs/walk.ts:104:22)
    at async collectDir (https://deno.land/x/fresh@1.2.0/src/dev/mod.ts:31:20)
    at async Promise.all (index 0)
    at async collect (https://deno.land/x/fresh@1.2.0/src/dev/mod.ts:47:29)
    at async https://deno.land/x/fresh@1.2.0/update.ts:188:18
PS C:\<redacted_path>\fresh>
```

It does not find fresh\src\routes.

Folder tree:
```bash
fresh
│   .gitignore
│   .gitlab-ci.yml
│   deno.json
│   Dockerfile
│   README.md
│
├───.vscode
│       extensions.json
│       settings.json
│
└───src
    │   dev.ts
    │   fresh.gen.ts
    │   main.ts
    │   twind.config.ts
    │
    ├───components
    │       Button.tsx
    │
    ├───islands
    │       Counter.tsx
    │
    ├───routes
    │   │   index.tsx
    │   │   [name].tsx
    │   │
    │   └───api
    │           joke.ts
    │
    └───static
            favicon.ico
            logo.svg
```

Hope that help :p

**Comment by marvinhagemeister** [comment]
Leaving a note: Since this is not a config option, there is no way for us to know up front where the project was moved to. One approach could be to crawl the current directory tree and look for `fresh.gen.ts` or some other fresh specific file. That would likely be a good enough approximation.

**Comment by deer** [comment]
I got this sorted and tested; look for a PR tomorrow, after I write up why it's harder than it first appears.
