### ISSUE TITLE
fresh@main errors on deploy

### ISSUE THREAD

**Issue by satyarohith** [denoland/fresh#135]
Works well locally but errors out with the below error on deploy.
```
TypeError: Must be a file URL.
    at fromFileUrl (https://deno.land/std@0.128.0/path/posix.ts:408:15)
    at Function.fromManifest (https://raw.githubusercontent.com/lucacasonato/fresh/main/src/server/context.ts:135:48)
    at start (https://raw.githubusercontent.com/lucacasonato/fresh/main/src/server/mod.ts:6:37)
    at https://raw.githubusercontent.com/satyarohith/www/b472677ffe9cafc4419b65412436bc2a2684c37a/main.ts:8:7
```

Crash Report: https://dash.deno.com/projects/satyarohith/deployments/xwwjvwc6d2sg/crashes/bb535b36-1984-40c0-953e-242d950f5de7

Repo: https://github.com/satyarohith/www

**Comment by crowlKats** [comment]
This problem is the same we faced with updating dotland, has to do with the change of `import.meta.url`

**Comment by lucacasonato** [comment]
You need to use a Deno Deploy project created after August 31st 2021.
