### ISSUE TITLE
Running deno test -A not working (development)

### ISSUE THREAD

**Issue by wtchen** [denoland/fresh#1403]
This is an awesome project (love the simplicity of this framework). I'm looking to learn about how Fresh works and contribute. 

Assuming that the tests are supposed to be passing on the main branch, I'm unable to get the tests to run properly.

### Context
* WSL 2 on Windows 10,  Ubuntu 22.04.1 LTS
* Deno installed at `/home/wchen/.deno/bin/deno`

### Steps to reproduce

1. Pull this repo and then `cd fresh`
2. Run `deno test -A`; for me 28 tests in 2 steps failed, I got the following error on each one:

  ```
  error: Error: Could not find browser revision 1022525. Run "PUPPETEER_PRODUCT=chrome deno run -A --unstable https://deno.land/x/puppeteer@16.2.0/install.ts" to download a supported browser binary.
        if (missingText) throw new Error(missingText);
                               ^
      at ChromeLauncher.launch (https://deno.land/x/puppeteer@16.2.0/src/deno/Launcher.ts:99:30)
      at eventLoopTick (ext:core/01_core.js:183:11)
      at async setUpServer (file:///mnt/c/Users/wchen/projects/fresh/tests/twind_test.ts:18:19)
      at async fn (file:///mnt/c/Users/wchen/projects/fresh/tests/twind_test.ts:192:20)
  ```

3. Run `PUPPETEER_PRODUCT=chrome deno run -A --unstable https://deno.land/x/puppeteer@16.2.0/install.ts`. I got another error, this is more cryptic:
```
error: Interrupted: operation canceled
    const result = await reader.read(inspectArr);
                   ^
    at async read (ext:deno_io/12_io.js:103:17)
    at async readDelim (https://deno.land/std@0.93.0/io/bufio.ts:652:20)
    at async readStringDelim (https://deno.land/std@0.93.0/io/bufio.ts:702:20)
    at async readLines (https://deno.land/std@0.93.0/io/bufio.ts:711:18)
    at async waitForWSEndpoint (https://deno.land/x/puppeteer@16.2.0/src/deno/BrowserRunner.ts:168:20)
    at async BrowserRunner.setupConnection (https://deno.land/x/puppeteer@16.2.0/src/deno/BrowserRunner.ts:146:31)
    at async ChromeLauncher.launch (https://deno.land/x/puppeteer@16.2.0/src/deno/Launcher.ts:114:26)
    at async withPageName (file:///mnt/c/Users/wchen/projects/fresh/tests/test_utils.ts:43:21)
    at async fn (file:///mnt/c/Users/wchen/projects/fresh/tests/islands_test.ts:332:5)
```

I tried running the tests as root, but I get a separate error (this is after updating Puppeteer):

```
error: NotFound: No such file or directory (os error 2)
    this.proc = Deno.run({
                     ^
    at opRun (ext:runtime/40_process.js:46:14)
    at Object.run (ext:runtime/40_process.js:132:15)
    at BrowserRunner.start (https://deno.land/x/puppeteer@16.2.0/src/deno/BrowserRunner.ts:64:22)
    at ChromeLauncher.launch (https://deno.land/x/puppeteer@16.2.0/src/deno/Launcher.ts:108:12)
    at eventLoopTick (ext:core/01_core.js:183:11)
    at async setUpServer (file:///mnt/c/Users/wchen/projects/fresh/tests/twind_test.ts:18:19)
    at async fn (file:///mnt/c/Users/wchen/projects/fresh/tests/twind_test.ts:118:20)
```

Not sure where to go from here. The error seems to be coming from the OS, but the fact that it doesn't run under root is strange.

**Comment by marvinhagemeister** [comment]
Puppeteer needs to be installed before running the tests. This can be done by running `deno task install-puppeteer` in the root of the repo.

**Comment by eridyk** [comment]
Sorry to reopen this issue but I face the same problem with this error message :

> error: Interrupted: operation canceled
>     const result = await reader.read(inspectArr);
>                    ^
>     at async read (ext:deno_io/12_io.js:103:17)
>     at async readDelim (https://deno.land/std@0.93.0/io/bufio.ts:652:20)
>     at async readStringDelim (https://deno.land/std@0.93.0/io/bufio.ts:702:20)
>     at async readLines (https://deno.land/std@0.93.0/io/bufio.ts:711:18)
>     at async waitForWSEndpoint (https://deno.land/x/puppeteer@16.2.0/src/deno/BrowserRunner.ts:168:20)
>     at async BrowserRunner.setupConnection (https://deno.land/x/puppeteer@16.2.0/src/deno/BrowserRunner.ts:146:31)
>     at async ChromeLauncher.launch (https://deno.land/x/puppeteer@16.2.0/src/deno/Launcher.ts:114:26)
>     at async file:///home/user/test.ts:22:17

The only difference with the error that @wtchen mentioned is that it does not crash on the withPageName function but on a line where I simply launch puppeteer, here is the line #22 of my script : `const browser = await puppeteer.launch();`

Then I am stuck at the step you mentioned : running `deno task install-puppeteer`. 

When I run it, I have a single line display : `error: No config file found` with no other explanation... do you have a clue for me please  :) ? Thanks for the help ^^
