### ISSUE TITLE
Introduce development time checks to remove remaining foot guns in the project

### ISSUE THREAD

**Issue by deer** [denoland/fresh#1416]
I read our documentation and found the following assumptions in the getting started and concepts pages. But we don't check for any of these to give good error messages.

- Only one _app.tsx is allowed per application and it must have default export
- One 500.tsx and it must have default export
- One 404.tsx and it must have default export
- Pascal case or kebab case islands (island name)
- Route must have handler or component
- If static override, ensure there is no normal static directory
- Static file conflict with routes (because static files have higher priority)
- Plugin doesn't call render
- Plugin Each defined module must be a JavaScript/TypeScript module

As an example, if you remove the default export from `_app.tsx` then the following unhelpful error message is presented (note how it doesn't mention `_app.tsx`:
```
An error occurred during route handling or page rendering. Error: Undefined component passed to createElement()

You likely forgot to export your component or might have mixed up default and named imports<#text params="[object Object]" url="http://localhost:8000/" route="/" data="undefined" Component="function Component() {}" />

  in #text

    at i.__b (https://esm.sh/stable/preact@10.15.1/denonext/debug.js:11:362)
    at k (https://esm.sh/v125/preact-render-to-string@6.1.0/X-ZS8q/denonext/preact-render-to-string.mjs:2:2086)
    at k (https://esm.sh/v125/preact-render-to-string@6.1.0/X-ZS8q/denonext/preact-render-to-string.mjs:2:2591)
    at k (https://esm.sh/v125/preact-render-to-string@6.1.0/X-ZS8q/denonext/preact-render-to-string.mjs:2:2591)
    at T (https://esm.sh/v125/preact-render-to-string@6.1.0/X-ZS8q/denonext/preact-render-to-string.mjs:2:1312)
    at renderInner (https://deno.land/x/fresh@1.2.0/src/server/render.ts:191:16)
    at renderSync (https://deno.land/x/fresh@1.2.0/src/server/render.ts:209:7)
    at https://deno.land/x/fresh@1.2.0/src/server/render.ts:240:38
    at Object.DEFAULT_RENDER_FN [as renderFn] (https://deno.land/x/fresh@1.2.0/src/server/context.ts:792:3)
    at renderAsync (https://deno.land/x/fresh@1.2.0/src/server/render.ts:240:18)
Error: Undefined component passed to createElement()

You likely forgot to export your component or might have mixed up default and named imports<#text params="[object Object]" url="http://localhost:8000/" route="" data="undefined" Component="function Component() {}" />

  in #text
  in Provider

    at i.__b (https://esm.sh/stable/preact@10.15.1/denonext/debug.js:11:362)
    at k (https://esm.sh/v125/preact-render-to-string@6.1.0/X-ZS8q/denonext/preact-render-to-string.mjs:2:2086)
    at k (https://esm.sh/v125/preact-render-to-string@6.1.0/X-ZS8q/denonext/preact-render-to-string.mjs:2:2591)
    at k (https://esm.sh/v125/preact-render-to-string@6.1.0/X-ZS8q/denonext/preact-render-to-string.mjs:2:2591)
    at T (https://esm.sh/v125/preact-render-to-string@6.1.0/X-ZS8q/denonext/preact-render-to-string.mjs:2:1312)
    at renderInner (https://deno.land/x/fresh@1.2.0/src/server/render.ts:191:16)
    at renderSync (https://deno.land/x/fresh@1.2.0/src/server/render.ts:209:7)
```

We should include some sort of development time set of checks to look for these sorts of misconfigurations / misunderstandings and let the developer know, so they don't spend time having to debug.

**Comment by deer** [comment]
As another example, if I create something like:
```tsx
//routes/test.tsx
export function Test() {
  return <div>hello</div>;
}
```
and then go to `localhost:8000/test` I get... nothing. This is due to throwing a 405 error from the `unknownMethodHandler`. That's not great, especially if the developer is expecting the route to work.

**Comment by marvinhagemeister** [comment]
Thanks for putting together the list. These are all great points and would make the DX for Fresh a lot better.

> As another example, if I create something like:
> 
> ```tsx
> //routes/test.tsx
> export function Test() {
>   return <div>hello</div>;
> }
> ```
> 
> and then go to `localhost:8000/test` I get... nothing. This is due to throwing a 405 error from the `unknownMethodHandler`. That's not great, especially if the developer is expecting the route to work.

That should just default to a GET handler and render the route. It should just work.

**Comment by lino-levan** [comment]
> That should just default to a GET handler and render the route. It should just work.

Even if it's not default exported?

**Comment by marvinhagemeister** [comment]
Ah good catch, no that should be an error.

**Comment by mbhrznr** [comment]
would love to tackle that as it might be quite a nice introduction to the "inners" of fresh.

**Comment by deer** [comment]
Hey @mbhrznr, unfortunately (for you, since you want to do this, and Marvin, since he has to review it!) I'm almost done with this. If you'd like, I can push what I have and let you take it over the finish line (some tests and cleanup) and create the PR.

**Comment by mbhrznr** [comment]
if you don't mind, sure! 🙏

**Comment by deer** [comment]
I've created https://github.com/deer/fresh/tree/1416_safety_checks with what I have. There's a sample project that's doing some bad things, and when you do `deno task start` from that folder, you should receive some messages.

**Comment by mbhrznr** [comment]
appreciating it!

**Comment by deer** [comment]
Ok that's a bit embarrassing. I created the branch but forgot to commit anything to it 🤦 

https://github.com/deer/fresh/commit/c9306c43fa0339fe96b57d83af8169c1c650daa3 actually has something to look at now 😅

**Comment by mbhrznr** [comment]
@deer once again: 
thanks for giving me the chance to take over! ❤️ 
as expected it was super interesting to get into.
your examples also made it incredible easy to add the remaining checks.
