### ISSUE TITLE
Errors with AoT Github Action

### ISSUE THREAD

**Issue by willpuckett** [denoland/fresh#1682]
I'm having an intermittent error with the GitHub action for AoT build. The build works locally, but the Github action throws SQL errors sometimes:

```
Download https://esm.sh/v131/use-sync-external-store@1.2.0/X-ZS8q/denonext/shim.js
Download https://esm.sh/v131/swr@2.2.0/X-ZS8q/denonext/_internal.js
Download https://deno.land/std@0.161.0/encoding/base64.ts
Download https://deno.land/std@0.150.0/media_types/vendor/mime-db.v1.52.0.ts
Download https://deno.land/std@0.150.0/media_types/_util.ts
error: Uncaught (in promise) Error: table data_version already exists in 
create table data_version (
  k integer primary key,
  version integer not null
);
insert into data_version (k, version) values (0, 0);
create table kv (
  k blob primary key,
  v blob not null,
  v_encoding integer not null,
  version integer not null
) without rowid;
 at offset 14: Error code 1: SQL error or missing database at ext:deno_kv/01_db.ts:8:17
  const manifest = (await import(toFileUrl(manifestPath).href))
                    ^
    at async build (https://deno.land/x/fresh@1.4.2/src/dev/build.ts:10:21)
    at async dev (https://deno.land/x/fresh@1.4.2/src/dev/dev_command.ts:38:5)
```

or 

```
Download https://esm.sh/v131/use-sync-external-store@1.2.0/X-ZS8q/denonext/shim.js
Download https://esm.sh/v131/swr@2.2.0/X-ZS8q/denonext/_internal.js
Download https://deno.land/std@0.161.0/encoding/base64.ts
Download https://deno.land/std@0.150.0/media_types/vendor/mime-db.v1.52.0.ts
Download https://deno.land/std@0.150.0/media_types/_util.ts
error: Uncaught (in promise) Error: table data_version already exists: Error code 1: SQL error or missing database at ext:deno_kv/01_db.ts:8:17
  const manifest = (await import(toFileUrl(manifestPath).href))
                    ^
    at async build (https://deno.land/x/fresh@1.4.1/src/dev/build.ts:10:21)
    at async dev (https://deno.land/x/fresh@1.4.1/src/dev/dev_command.ts:38:5)
```

In the successful run, the above section produced the following output: 

```
Download https://esm.sh/v131/use-sync-external-store@1.2.0/X-ZS8q/denonext/shim.js
Download https://esm.sh/v131/swr@2.2.0/X-ZS8q/denonext/_internal.js
Download https://deno.land/std@0.161.0/encoding/base64.ts
Download https://deno.land/std@0.150.0/media_types/vendor/mime-db.v1.52.0.ts
Download https://deno.land/std@0.150.0/media_types/_util.ts
Download https://deno.land/x/fresh@1.4.2/src/runtime/entrypoints/main_dev.ts
Download https://deno.land/x/fresh@1.4.2/plugins/twindv1/main.ts
Download https://pax.deno.dev/denoland/fresh@main/src/server/types.ts
```

The project is using Deno KV, with the --unstable flag in the build command.

**Comment by marvinhagemeister** [comment]
Thanks for reporting! This sounds like an issue with Deno KV and not with Fresh. Here is the issue for this in the deno tracker https://github.com/denoland/deno/issues/20196 .
