### ISSUE TITLE
Intermittent 5xx errors when downloading islands using AOT Build in Fresh 1.4.2

### ISSUE THREAD

**Issue by mcandeia** [denoland/fresh#1724]
**Description:**
We've changed our project to use AOT builds + fresh version 1.4.2, this seemed to work fine but we are noticing a small window where islands downloads returns 5xx errors. We are using deno deploy you can see the errors on the attached screenshot below

<img width="956" alt="image" src="https://github.com/denoland/fresh/assets/5839364/834648bd-b0e8-47c6-9e65-58e5ebfcdfad">

```text
UnexpectedEof: unexpected EOF during chunk size line: readfile '/src/_fresh/chunk-HXXG4SMD.js.map'
    at async Object.readFile (ext:deno_fs/30_fs.js:718:18)
    at async https://denopkg.com/denoland/fresh@1.4.2/src/server/context.ts:186:29
    at async Promise.all (index 156)
    at async Function.fromManifest (https://denopkg.com/denoland/fresh@1.4.2/src/server/context.ts:184:11)
    at async start (https://denopkg.com/denoland/fresh@1.4.2/src/server/mod.ts:113:15)
    at async file:///src/main.ts:15:1
````

it's important to notice that this error occurs to all islands. The setup of the AOT builds are exactly the same as explained [here](https://fresh.deno.dev/docs/concepts/ahead-of-time-builds)`deno task build + deployctl action`.

**Comment by marvinhagemeister** [comment]
That's strange, it seems like something failed in deploy while reading the file. So far I can't find anything to fault in Fresh itself. I've reached out to the deploy team internally to help investigate.

**Comment by marvinhagemeister** [comment]
Looking at this a little more, I'm pretty confident that the issue isn't in Fresh. Moving to the deploy issue tracker.
