### ISSUE TITLE
Can't get environment variables when prebuilding by Github worflow

### ISSUE THREAD

**Issue by ieiekk** [denoland/fresh#1843]
This is what I wrote in utils.ts:
```typescript
export const supabase = createClient<Database>(
  Deno.env.get("SUPABASE_URL") as string,
  Deno.env.get("SUPABASE_KEY") as string,
);
```
After I push the commit, I got this error message on GIthub workflow page:
```typescirpt
Build step >
Run deno task build
Task build deno run -A dev.ts build
.
.
.
.
error: Uncaught (in promise) Error: supabaseUrl is required.
    at new p (https://esm.sh/v132/@supabase/supabase-js@2.4.0/esnext/supabase-js.mjs:2:2168)
    at nt (https://esm.sh/v132/@supabase/supabase-js@2.4.0/esnext/supabase-js.mjs:2:5286)
    at file:///home/runner/work/a-pp-greeting-cards-platform/a-pp-greeting-cards-platform/utils/utils.ts:20:25
Error: Process completed with exit code 1.
```

And I've setup the env var on deno deploy dashboard and this works on local .env file.

**Comment by martinrempel** [comment]
Did you set up [variables](https://docs.github.com/en/actions/learn-github-actions/variables) or [secrets](https://docs.github.com/en/actions/security-guides/using-secrets-in-github-actions)?

**Comment by marvinhagemeister** [comment]
@ieiekk Do you happen to use a setup with a `fresh.config.ts` or without one? Asking because before we introduced `fresh.config.ts` the `dev.ts` would always load `main.ts` which in turn imports every file of the application. In doing so it will encounter the `supabase` call and complain that the environment variables are not set. That's the main reason we introduced the `fresh.config.ts` which allows us to properly split the development mode internally so that you can create a build without loading `main.ts`

**Comment by ieiekk** [comment]
> Did you set up [variables](https://docs.github.com/en/actions/learn-github-actions/variables) or [secrets](https://docs.github.com/en/actions/security-guides/using-secrets-in-github-actions)?

I setup the secrets in Github workflow, but still got the same error.

**Comment by ieiekk** [comment]
> Did you set up [variables](https://docs.github.com/en/actions/learn-github-actions/variables) or [secrets](https://docs.github.com/en/actions/security-guides/using-secrets-in-github-actions)?

This works! I add SUPABASE_URL and SUPABASE_KEY as secrets:

<img width="1208" alt="Screenshot 2023-10-04 at 11 40 42 PM" src="https://github.com/denoland/fresh/assets/89718310/3bba401d-e3e1-48b4-bbc8-b6bb6a1b961d">

And add these lines in my deploy.yml:

```diff
name: Deploy
on:
  push:
    branches: [master, develope]
  pull_request:
    branches: master

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Install Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Build step
+        env: 
+            SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
+            SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: "deno task build"

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: "pp-greeting-cards-platform"
          entrypoint: "./main.ts"
```

Hope this helps anyone encountered the same issue.

**Comment by ieiekk** [comment]
> @ieiekk Do you happen to use a setup with a `fresh.config.ts` or without one? Asking because before we introduced `fresh.config.ts` the `dev.ts` would always load `main.ts` which in turn imports every file of the application. In doing so it will encounter the `supabase` call and complain that the environment variables are not set. That's the main reason we introduced the `fresh.config.ts` which allows us to properly split the development mode internally so that you can create a build without loading `main.ts`

I leave that file as default:
```typescript
import { defineConfig } from "$fresh/server.ts";
import twindPlugin from "$fresh/plugins/twind.ts";
import twindConfig from "./twind.config.ts";
export default defineConfig({
  plugins: [twindPlugin(twindConfig)],
});
```
So is there a way to avoid import some files during build time?  Thanks in advance 🙏

**Comment by avalero** [comment]
Same here, no way to make the build step in github actions without env variables. That is somehow unexpected as they are server side variables @marvinhagemeister

**Comment by JakeAve** [comment]
I think there needs to be a way to know which variables will be needed. The only way I could verify which variables are needed for the build to not crash was by renaming my local .env and trying a local build. It appears the secrets are overwritten once the server is running and the environment variables are loaded in anyway.
