### ISSUE TITLE
Form Submission Example Code Fails

### ISSUE THREAD

**Issue by marktyers** [denoland/fresh#1897]
Working through the latest Deno Fresh Tutorial and get an error on [Form Submissions](https://fresh.deno.dev/docs/getting-started/form-submissions)

Created the `routes/search.tsx` file and pasted in the provided code:

```typescript
const NAMES = ["Alice", "Bob", "Charlie", "Dave", "Eve", "Frank"];

interface Data {
  results: string[];
  query: string;
}

export const handler: Handlers<Data> = {
  GET(req, ctx) {
    const url = new URL(req.url);
    const query = url.searchParams.get("q") || "";
    const results = NAMES.filter((name) => name.includes(query));
    return ctx.render({ results, query });
  },
};

export default function Page({ data }: PageProps<Data>) {
  const { results, query } = data;
  return (
    <div>
      <form>
        <input type="text" name="q" value={query} />
        <button type="submit">Search</button>
      </form>
      <ul>
        {results.map((name) => <li key={name}>{name}</li>)}
      </ul>
    </div>
  );
}
```

This triggers the following error:

```
error: Uncaught (in promise) TypeError: The module's source code could not be parsed: Expected '>', got 'type' at file:///.../routes/search.ts:24:16

          <input type="text" name="q" value={query} />
                 ~~~~
  const manifest = (await import(toFileUrl(join(dir, "fresh.gen.ts")).href))
                    ^
    at async dev (https://deno.land/x/fresh@1.4.3/src/dev/dev_command.ts:42:21)
    at async file:///home/codio/workspace/dev.ts:5:1
```

Looks like it does not like attributes in the JSX code. Removed the **type** attribute and the error is on the **name"" attribute. so there is clearly a problem with the tutorial code. Any thoughts?

```
deno 1.37.1 (release, x86_64-unknown-linux-gnu)
v8 11.8.172.6
typescript 5.2.2
fresh 1.4.3
```

**Comment by marvinhagemeister** [comment]
@marktyers JSX only works in `.tsx` files not in `.ts` files. Renaming your file to have the `.tsx` extension should resolve this.
