### ISSUE TITLE
An error occurred during route handling or page rendering. Error: Build failed with 1 error: error: [unreachable] Not an ESM module.

### ISSUE THREAD

**Issue by JacobWeisenburger** [denoland/fresh#2063]
I keep getting this error and have no idea what to do about it. Please help.

```
An error occurred during route handling or page rendering. Error: Build failed with 1 error:
error: [unreachable] Not an ESM module.
    at failureErrorWithLog (https://deno.land/x/esbuild@v0.17.11/mod.js:1612:15)
    at https://deno.land/x/esbuild@v0.17.11/mod.js:1024:25
    at runOnEndCallbacks (https://deno.land/x/esbuild@v0.17.11/mod.js:1447:45)
    at buildResponseToResult (https://deno.land/x/esbuild@v0.17.11/mod.js:1022:7)
    at https://deno.land/x/esbuild@v0.17.11/mod.js:1051:16
    at responseCallbacks.<computed> (https://deno.land/x/esbuild@v0.17.11/mod.js:673:9)
    at handleIncomingPacket (https://deno.land/x/esbuild@v0.17.11/mod.js:728:9)
    at readFromStdout (https://deno.land/x/esbuild@v0.17.11/mod.js:649:7)
    at https://deno.land/x/esbuild@v0.17.11/mod.js:1898:11
    at eventLoopTick (ext:core/01_core.js:178:11) {
  errors: [
    {
      detail: Error: [unreachable] Not an ESM module.
    at NativeLoader.loadEsm (https://raw.githubusercontent.com/lucacasonato/esbuild_deno_loader/8031f71afa1bbcd3237a94b11f53a2e5c5c0e7bf/src/native_loader.ts:36:13)
    at eventLoopTick (ext:core/01_core.js:178:11)
    at async requestCallbacks.on-load (https://deno.land/x/esbuild@v0.17.11/mod.js:1397:22)
    at async handleRequest (https://deno.land/x/esbuild@v0.17.11/mod.js:699:13),
      id: "",
      location: null,
      notes: [],
      pluginName: "deno",
      text: "[unreachable] Not an ESM module."
    }
  ],
  warnings: []
}
```

**Comment by JacobWeisenburger** [comment]
Closed in favor of:
https://github.com/denoland/fresh/issues/1103
