### ISSUE TITLE
can't access fresh app via internal url with dokku

### ISSUE THREAD

**Issue by abdulbasetbasher** [denoland/fresh#2067]
I deployed a fresh app to Dokku, and the app works fine with the Nginx proxy. However, when I try to connect to the app from another Dokku app internally, it fails.

```
2023-11-26T17:22:29.616238349Z app[web.1]:
2023-11-26T17:22:29.616324020Z app[web.1]:  🍋 Fresh ready
2023-11-26T17:22:29.616329360Z app[web.1]:     Local: http://localhost:5000/
2023-11-26T17:22:29.616333558Z app[web.1]:
2023-11-26T17:23:06.584808195Z app[web.1]: TypeError: Invalid URL: 'http://test-app.web.1:5000/'
2023-11-26T17:23:06.584886222Z app[web.1]:     at getSerialization (ext:deno_url/00_url.js:89:11)
2023-11-26T17:23:06.584890259Z app[web.1]:     at new URL (ext:deno_url/00_url.js:380:27)
2023-11-26T17:23:06.584893315Z app[web.1]:     at handler (https://deno.land/x/fresh@1.5.4/src/server/context.ts:508:19)
2023-11-26T17:23:06.584896260Z app[web.1]:     at https://deno.land/x/fresh@1.5.4/src/server/boot.ts:69:9
2023-11-26T17:23:06.584899166Z app[web.1]:     at ext:deno_http/00_serve.js:532:28
2023-11-26T17:23:06.584901931Z app[web.1]:     at ext:deno_http/00_serve.js:730:29
2023-11-26T17:23:06.584904676Z app[web.1]:     at eventLoopTick (ext:core/01_core.js:183:11)
2023-11-26T17:23:06.584907612Z app[web.1]:     at async bootServer (https://deno.land/x/fresh@1.5.4/src/server/boot.ts:66:5)
2023-11-26T17:23:06.584910517Z app[web.1]:     at async startServer (https://deno.land/x/fresh@1.5.4/src/server/boot.ts:27:5)
2023-11-26T17:23:06.584913382Z app[web.1]:     at async start (https://deno.land/x/fresh@1.5.4/src/server/mod.ts:109:3)
```

**Comment by marvinhagemeister** [comment]
Nothing we can do about that. The string `http://test-app.web.1:5000/` is not a valid URL. Maybe something in Dokku is configured wrong?
