### ISSUE TITLE
fresh init creates broken example — [plugin deno] The module was missing and could not be loaded.

### ISSUE THREAD

**Issue by vibegui** [denoland/fresh#214]
Repro (simple fresh init) https://github.com/deco-pages/edge-store

```
fresh init .
Check https://raw.githubusercontent.com/lucacasonato/fresh/main/cli.ts
The manifest has been generated for 3 routes and 1 islands.

deno task start
Warning deno task is unstable and may drastically change in the future
Task start deno run -A --watch --no-check main.ts
Watcher Process started.
Server listening on http://localhost:8000
✘ [ERROR] [plugin deno] The module was missing and could not be loaded.

    deno:file:///Users/guilherme/Projects/deco-pages/edge-store/islands/Counter.tsx:2:40:
      2 │ import { h, IS_BROWSER, useState } from "$fresh/runtime.ts";
        ╵                                         ~~~~~~~~~~~~~~~~~~~

An error occured during route handling or page rendering. Error: Build failed with 1 error:
deno:file:///Users/guilherme/Projects/deco-pages/edge-store/islands/Counter.tsx:2:40: ERROR: [plugin: deno] The module was missing and could not be loaded.
    at failureErrorWithLog (https://deno.land/x/esbuild@v0.14.34/mod.js:1572:15)
    at https://deno.land/x/esbuild@v0.14.34/mod.js:1218:28
    at runOnEndCallbacks (https://deno.land/x/esbuild@v0.14.34/mod.js:1001:63)
    at buildResponseToResult (https://deno.land/x/esbuild@v0.14.34/mod.js:1216:7)
    at https://deno.land/x/esbuild@v0.14.34/mod.js:1325:14
    at https://deno.land/x/esbuild@v0.14.34/mod.js:633:9
    at handleIncomingPacket (https://deno.land/x/esbuild@v0.14.34/mod.js:730:9)
    at readFromStdout (https://deno.land/x/esbuild@v0.14.34/mod.js:599:7)
    at https://deno.land/x/esbuild@v0.14.34/mod.js:1846:11
An error occured during route handling or page rendering. Error: Build failed with 1 error:
deno:file:///Users/guilherme/Projects/deco-pages/edge-store/islands/Counter.tsx:2:40: ERROR: [plugin: deno] The module was missing and could not be loaded.
    at failureErrorWithLog (https://deno.land/x/esbuild@v0.14.34/mod.js:1572:15)
    at https://deno.land/x/esbuild@v0.14.34/mod.js:1218:28
    at runOnEndCallbacks (https://deno.land/x/esbuild@v0.14.34/mod.js:1001:63)
    at buildResponseToResult (https://deno.land/x/esbuild@v0.14.34/mod.js:1216:7)
    at https://deno.land/x/esbuild@v0.14.34/mod.js:1325:14
    at https://deno.land/x/esbuild@v0.14.34/mod.js:633:9
    at handleIncomingPacket (https://deno.land/x/esbuild@v0.14.34/mod.js:730:9)
    at readFromStdout (https://deno.land/x/esbuild@v0.14.34/mod.js:599:7)
    at https://deno.land/x/esbuild@v0.14.34/mod.js:1846:11
^C
```

**Comment by lucacasonato** [comment]
Please update your fresh version. To install the latest from `main`:

```
deno install -A -f --no-check -n fresh -r https://raw.githubusercontent.com/lucacasonato/fresh/c299d7b6a4bf452d4db62161f4fd701ff3b74d4c/cli.ts
```

**Comment by vibegui** [comment]
Thanks! That works. I tried with `master` but I guess deno was caching it locally.
