### ISSUE TITLE
Fresh Docs website fails to navigate from Docs to Showcase or Components when the Table of Contents appear collapsed

### ISSUE THREAD

**Issue by king8fisher** [denoland/fresh#2190]
The error is thrown in the browser:
```
main.js:1 Fetch finished loading: GET "https://fresh.deno.dev/showcase?fresh-partial=true".
S @ main.js:1
(anonymous) @ main.js:1
main.js:1 Uncaught (in promise) Error: Found no partials in HTML response. Please make sure to render at least one partial. Requested url: https://fresh.deno.dev/showcase?fresh-partial=true
    at ce (main.js:1:6200)
    at async S (main.js:1:4601)
    at async HTMLDocument.<anonymous> (main.js:1:8950)
ce @ main.js:1
```

**Comment by stepbrobd** [comment]
had the same issue (Deno 1.39.1 Fresh 1.6.1)

```
Uncaught (in promise) Error: Found no partials in HTML response. Please make sure to render at least one partial. Requested url: https://some-url?fresh-partial=true
    at ue (main.js:1:6925)
    at async H (main.js:1:5393)
    at async HTMLDocument.<anonymous> (main.js:1:9575)
ue @ main.js:1
```

Only happens on production build (with `_fresh` and `DENO_DEPLOYMENT_ID` set), cannot reproduce when running with `deno task start`
