### ISSUE TITLE
Failed to execute 'pipeTo' on 'ReadableStream'

### ISSUE THREAD

**Issue by hemanth** [denoland/fresh#238]
```
~/labs via  v18.1.0 via 🐍 v2.7.16 via 💎 v3.1.0 
❯ deno run -A --no-check --allow-net --unsafely-ignore-certificate-errors https://raw.githubusercontent.com/lucacasonato/fresh/main/init.ts my-app
DANGER: TLS certificate validation is disabled for all hostnames
The target directory is not empty (files could get overwritten). Do you want to continue anyway? [y/N] y
error: Uncaught (in promise) TypeError: Failed to execute 'pipeTo' on 'ReadableStream': Argument 1 is not of type WritableStream.
  await raw.pipeTo(proc.stdin.writable);
            ^
    at makeException (deno:ext/webidl/00_webidl.js:79:12)
    at Array.WritableStream (deno:ext/webidl/00_webidl.js:866:15)
    at ReadableStream.pipeTo (deno:ext/web/06_streams.js:4285:41)
    at generate (https://raw.githubusercontent.com/lucacasonato/fresh/main/src/dev/mod.ts:127:13)
    at https://raw.githubusercontent.com/lucacasonato/fresh/main/init.ts:218:7
```

**Comment by lucacasonato** [comment]
Mh, what is your Deno version? You need to be on the latest release. You can upgrade with `deno upgrade`.

**Comment by hemanth** [comment]
Ah, righto. 

Also, I am in a guarded env, so:

```
❯ deno task start --unsafely-ignore-certificate-errors
Warning deno task is unstable and may drastically change in the future
Task start deno run -A --watch=static/,routes/,islands/ --no-check dev.ts "--unsafely-ignore-certificate-errors"
Watcher Process started.
Download https://raw.githubusercontent.com/lucacasonato/fresh/main/dev.ts
Sending fatal alert BadCertificate
error: error sending request for url (https://raw.githubusercontent.com/lucacasonato/fresh/main/dev.ts): error trying to connect: invalid peer certificate contents: invalid peer certificate: UnknownIssuer
    at file:///Users/hhegadehallimadh/labs/my-app/dev.ts:3:17
Watcher Process finished. Restarting on file change...
```

Is there an ENV VAR that I can set to skip cert checks?

**Comment by lucacasonato** [comment]
`DENO_TLS_CA_STORE=system` will cause Deno to use your system CA certs. Alternatively put the `--unsafely-ignore-certificate-errors` before the `dev.ts` in the `"start"` task in `deno task`.

**Comment by hemanth** [comment]
Thanks. Had to `-- --unsafely-ignore-certificate-errors`.

But then: 

```
❯ deno task start 
Warning deno task is unstable and may drastically change in the future
Task start deno run -A --watch=static/,routes/,islands/ --no-check dev.ts
Watcher Process started.
The manifest has been generated for 3 routes and 1 islands.
Server listening on http://localhost:8000
^[[OAn error occured during route handling or page rendering. Error: Invalid gzip data in archive: InvalidInput: invalid gzip header
    at extractFileFromTarGzip (https://deno.land/x/esbuild@v0.14.39/mod.js:1755:11)
    at installFromNPM (https://deno.land/x/esbuild@v0.14.39/mod.js:1708:22)
    at async install (https://deno.land/x/esbuild@v0.14.39/mod.js:1789:12)
    at async https://deno.land/x/esbuild@v0.14.39/mod.js:1800:23
An error occured during route handling or page rendering. Error: Invalid gzip data in archive: InvalidInput: invalid gzip header
    at extractFileFromTarGzip (https://deno.land/x/esbuild@v0.14.39/mod.js:1755:11)
    at installFromNPM (https://deno.land/x/esbuild@v0.14.39/mod.js:1708:22)
    at async install (https://deno.land/x/esbuild@v0.14.39/mod.js:1789:12)
    at async https://deno.land/x/esbuild@v0.14.39/mod.js:1800:23
error: Error: Invalid gzip data in archive: InvalidInput: invalid gzip header
    at extractFileFromTarGzip (https://deno.land/x/esbuild@v0.14.39/mod.js:1755:11)
    at installFromNPM (https://deno.land/x/esbuild@v0.14.39/mod.js:1708:22)
    at async install (https://deno.land/x/esbuild@v0.14.39/mod.js:1789:12)
    at async https://deno.land/x/esbuild@v0.14.39/mod.js:1800:23
Watcher Process finished. Restarting on file change...
```

```
❯ deno --version
deno 1.23.0 (release, x86_64-apple-darwin)
v8 10.4.132.5
typescript 4.7.2
```

**Comment by lucacasonato** [comment]
Can you send me your `deno.json` file contents? `-- --unsafely-ignore-certificate-errors` doesn't seem quite right. It seems to be failing on downloading of the esbuild binary.

**Comment by lucacasonato** [comment]
Closing because of non response.
