### ISSUE TITLE
TypeError: Cannot read properties of null (reading '__hooks')

### ISSUE THREAD

**Issue by ooker777** [denoland/fresh#2586]
```jsx
import { useEffect } from "https://esm.sh/v128/preact@10.19.6/hooks/src/index.js";

export default function Island() {
  useEffect(()=> {
    newFunction();
    function newFunction() {
      console.log('foo');
    }
    console.log('bar');
  }) 
  return <>Text</>
}
```
Error:
```
An error occurred during route handling or page rendering.

  3 | 
  4 | export default function Island() {
> 5 |   useEffect(()=> {
    |   ^
  6 |     newFunction();
  7 |     function newFunction() {
  8 |       console.log('foo');

TypeError: Cannot read properties of null (reading '__hooks')
    at s (https://esm.sh/stable/preact@10.19.6/denonext/hooks/src.js:2:1339)
    at G (https://esm.sh/stable/preact@10.19.6/denonext/hooks/src.js:2:2385)
    at Object.Island (file:///D:/Programming/Test/fresh-project/islands/Island.jsx:5:3)
    at m (https://esm.sh/v135/preact-render-to-string@6.3.1/X-ZS8q/denonext/preact-render-to-string.mjs:2:3237)
    at m (https://esm.sh/v135/preact-render-to-string@6.3.1/X-ZS8q/denonext/preact-render-to-string.mjs:2:2543)
    at m (https://esm.sh/v135/preact-render-to-string@6.3.1/X-ZS8q/denonext/preact-render-to-string.mjs:2:3802)
    at m (https://esm.sh/v135/preact-render-to-string@6.3.1/X-ZS8q/denonext/preact-render-to-string.mjs:2:3802)
    at m (https://esm.sh/v135/preact-render-to-string@6.3.1/X-ZS8q/denonext/preact-render-to-string.mjs:2:3802)
    at m (https://esm.sh/v135/preact-render-to-string@6.3.1/X-ZS8q/denonext/preact-render-to-string.mjs:2:3802)
    at m (https://esm.sh/v135/preact-render-to-string@6.3.1/X-ZS8q/denonext/preact-render-to-string.mjs:2:3802)
```
# `deno.json`
```json
"imports": {
    "$fresh/": "https://deno.land/x/fresh@1.6.8/",
    "preact": "https://esm.sh/preact@10.19.6",
    "preact/": "https://esm.sh/preact@10.19.6/",
    "@preact/signals": "https://esm.sh/*@preact/signals@1.2.2",
    "@preact/signals-core": "https://esm.sh/*@preact/signals-core@1.5.1",
    "tailwindcss": "npm:tailwindcss@3.4.1",
    "tailwindcss/": "npm:/tailwindcss@3.4.1/",
    "tailwindcss/plugin": "npm:/tailwindcss@3.4.1/plugin.js",
    "$std/": "https://deno.land/std@0.216.0/"
  },
  "compilerOptions": {
    "jsx": "react-jsx",
    "jsxImportSource": "preact"
  },
```

**Comment by marvinhagemeister** [comment]
Mixing files from the publicly exported package entries and random files from any of the `src` folders is not supported. Please only use the public package entries.

```diff
- import { useEffect } from "https://esm.sh/v128/preact@10.19.6/hooks/src/index.js";
+ import { useEffect } from "preact/hooks";
```

**Comment by ooker777** [comment]
Check if [LSP only suggests the src path for all hooks, even when `preact` has been declared in the import map · Issue #24476 · denoland/deno](https://github.com/denoland/deno/issues/24476 "LSP only suggests the src path for all hooks, even when `preact` has been declared in the import map · Issue #24476 · denoland/deno")
