### ISSUE TITLE
Can not use react-select

### ISSUE THREAD

**Issue by hemedani** [denoland/fresh#2595]
Throw this error when use `react-select` library even with `npm` or `esm.sh`
```
Invalid type passed to createElement(): [object Object]

Error: Invalid type passed to createElement(): [object Object]
    at a.__b (https://esm.sh/stable/preact@10.19.6/denonext/debug.js:23:9)
    at m (https://esm.sh/v135/preact-render-to-string@6.3.1/X-ZS8q/denonext/preact-render-to-string.mjs:2:2611)
    at m (https://esm.sh/v135/preact-render-to-string@6.3.1/X-ZS8q/denonext/preact-render-to-string.mjs:2:2543)
    at m (https://esm.sh/v135/preact-render-to-string@6.3.1/X-ZS8q/denonext/preact-render-to-string.mjs:2:5050)
    at m (https://esm.sh/v135/preact-render-to-string@6.3.1/X-ZS8q/denonext/preact-render-to-string.mjs:2:2543)
    at m (https://esm.sh/v135/preact-render-to-string@6.3.1/X-ZS8q/denonext/preact-render-to-string.mjs:2:5050)
    at m (https://esm.sh/v135/preact-render-to-string@6.3.1/X-ZS8q/denonext/preact-render-to-string.mjs:2:3802)
    at m (https://esm.sh/v135/preact-render-to-string@6.3.1/X-ZS8q/denonext/preact-render-to-string.mjs:2:5050)
    at m (https://esm.sh/v135/preact-render-to-string@6.3.1/X-ZS8q/denonext/preact-render-to-string.mjs:2:3802)
    at m (https://esm.sh/v135/preact-render-to-string@6.3.1/X-ZS8q/denonext/preact-render-to-string
```

And this is the `LSP Diagnostic` error message
```
'Select' cannot be used as a JSX component.
  Its type 'StateManagedSelect' is not a valid JSX element type.
    Type 'StateManagedSelect' is not assignable to type 'FunctionComponent<any>'.
      Call signature return types 'ReactElement<any, string | JSXElementConstructor<any>>' and 'VNode<any> | null' are incompatible.
        The types of 'type' are incompatible between these types.
          Type 'string | JSXElementConstructor<any>' is not assignable to type 'string | ComponentType<any>'.
            Type '(props: any, deprecatedLegacyContext?: any) => ReactNode' is not assignable to type 'string | ComponentType<any>'.
              Type '(props: any, deprecatedLegacyContext?: any) => ReactNode' is not assignable to type 'FunctionComponent<any>'.
                Type 'ReactNode' is not assignable to type 'VNode<any> | null'.
                  Type 'undefined' is not assignable to type 'VNode<any> | null'.
```

**Comment by CAYdenberg** [comment]
You'll have to set up preact-compat to use React libraries ... you can give some of the approaches here a shot: https://github.com/denoland/fresh/discussions/432

**Comment by bartlomieju** [comment]
Still broken on Fresh 2.2.x, but with a different root cause now. The original error was duplicate Preact versions via esm.sh (Fresh 1.x). In Fresh 2 with Vite, the React→Preact aliasing works, but `react-select` fails during SSR due to the CJS interop issue:

```
module is not defined
  at @babel/runtime/helpers/extends.js
```

`react-select` → `@emotion/react` → `@babel/runtime` — the `@babel/runtime` helpers are CJS and use `module.exports`, which Vite's SSR module runner doesn't support.

**Workaround**: Externalize the dependency chain so Deno loads them natively:

```ts vite.config.ts
export default defineConfig({
  plugins: [fresh()],
  ssr: {
    external: ["react-select", "@emotion/react", "@emotion/styled", "@babel/runtime"],
  },
});
```

This is a duplicate of the broader CJS/ESM interop issue #3653.

**Comment by bartlomieju** [comment]
Closing as duplicate of #3653 which tracks the broader CJS/ESM interop issue affecting many npm packages in Fresh 2's Vite SSR.
