### ISSUE TITLE
"Uncaught (in promise) TypeError: Expected ';', '}' (...)" error when importing css from highlight.js

### ISSUE THREAD

**Issue by crillion** [denoland/fresh#2614]
I'm trying to syntax highlight some code with highlight.js used with deno / fresh. My failed attempts are with the current versions of deno/fresh/highlight.js at august 7, 2024. I'm working on Windows 10, from PowerShell, where I've installed Deno.

To create my project I follow these steps :

- I go to a root folder: cd (...)/deno_apps
- I create a fresh project:
`deno run -A -r https://fresh.deno.dev`

- I specify for the project the name code_highlighter
- to the question "do you want to use a styling library?" I answer yes / tailwind.css
- to the question "do you use Visual Studio Code?" I answer no (I'm using notepad++) -> the project is created
- I enter the folder of my project cd code_highlighter
- I download highlight.js npm install highlight.js -> highlight.js is installed.
- I then edit code_highlighter/routes/index.ts as follows (the code is aimed to show both the source code highlighted, with colors and indentation, and the html string generated by highlight.js) :
° !!! please note the commented import on the default css style import from highlight.js

```
import { Head } from "$fresh/runtime.ts";
import hljs from 'highlight.js/lib/core';
import cpp from 'highlight.js/lib/languages/cpp';
//import 'highlight.js/styles/default.css';

const createMarkup = (htmlString) => {
  return { __html: htmlString };
};
export default function Home() {
  const codeTxt = '#include <iostream>\nint main() {}';
  hljs.registerLanguage('cpp', cpp);  
  const highlightedCode = hljs.highlight(
    codeTxt,
    { language: 'cpp' }
  ).value;
  return (
    <div>
      <pre>
        <code dangerouslySetInnerHTML={createMarkup(highlightedCode)}>
        </code>
      </pre>
      <div>
          {highlightedCode}
      </div>
    </div>
  );
}
```

- I launch the application with:
`deno task start`
as output I get:
```
#include <iostream>
int main() {}

<span class="hljs-meta">#<span class="hljs-keyword">include</span> <span class="hljs-string">&lt;iostream&gt;</span></span> <span class="hljs-function"><span class="hljs-type">int</span> <span class="hljs-title">main</span><span class="hljs-params">()</span> </span>{}
```
What I observe is :

- the indentation is ok
- it looks like highlight.js has done some job, putting tags, classes, and so on
- I don't see color or style. I don't know what I'm missing.

if I uncomment the import of the default style from highlight.js :

`import 'highlight.js/styles/default.css';`

I get this error on the Powershell console :

```
Watcher File change detected! Restarting! error: Uncaught (in promise) TypeError: Expected ';', '}' or at file:///C:/Users/crill/data/temp/deno_apps/code_highlighter/node_modules/.deno/highlight.js@11.10.0/node_modules/highlight.js/styles/default.css:1:5`

pre code.hljs { ~~~~ const manifest = (await import(toFileUrl(join(dir, "fresh.gen.ts")).href)) ^ at async dev (https://deno.land/x/fresh@1.6.8/src/dev/dev_command.ts:38:21) at async file:///C:/Users/crill/data/temp/deno_apps/code_highlighter/dev.ts:8:1 Watcher Process failed. Restarting on file change...
```

What am I doing wrong? What should I do to see also the color in the highlighted code?

**Comment by marvinhagemeister** [comment]
Importing CSS files is not supported in fresh as fresh doesn't transpile server code. CSS can only be loaded through a standard `<link>`-tag in HTML

**Comment by crillion** [comment]
thanks. but what exactly should I write in the href attribute of the link tag ?
I've tried
`<link rel="stylesheet" **href="../node_modules/highlight.js/styles/default.css"></link>`
but it doesn't work. How do I refer to a css file that's inside a folder inside node_modules ?

**Comment by invalidred** [comment]
Hey @crillion ... this is what I did for react mapbox component. I copied the css file to `static` folder and then added ref to link. Not ideal solution, but the css loaded.

```
<link rel="styleshee" href="/mapbox-gl.css" />
```

**Comment by marvinhagemeister** [comment]
Closing as duplicate of https://github.com/denoland/fresh/issues/1622 .
