### ISSUE TITLE
islands adapt  deno workspace

### ISSUE THREAD

**Issue by Octo8080X** [denoland/fresh#2615]
If deno workspace is used, islands will not function.

For example, the following error is shown.

```sh
Error: Build failed with 1 error:
components/Button.tsx:2:27: ERROR: [plugin: deno-resolver] specifier was a bare specifier, but was not remapped to anything by importMap.
    at failureErrorWithLog (https://deno.land/x/esbuild@v0.20.2/mod.js:1626:15)
    at https://deno.land/x/esbuild@v0.20.2/mod.js:1034:25
    at runOnEndCallbacks (https://deno.land/x/esbuild@v0.20.2/mod.js:1461:45)
    at buildResponseToResult (https://deno.land/x/esbuild@v0.20.2/mod.js:1032:7)
    at https://deno.land/x/esbuild@v0.20.2/mod.js:1061:16
    at responseCallbacks.<computed> (https://deno.land/x/esbuild@v0.20.2/mod.js:679:9)
    at handleIncomingPacket (https://deno.land/x/esbuild@v0.20.2/mod.js:739:9)
    at readFromStdout (https://deno.land/x/esbuild@v0.20.2/mod.js:655:7)
    at https://deno.land/x/esbuild@v0.20.2/mod.js:1974:11
    at eventLoopTick (ext:core/01_core.js:168:7) {
  errors: [Getter/Setter],
  warnings: [Getter/Setter]
}
```

In the case of building multiple fresh applications in a single repository, the availability of this feature should be very useful.

We would like to be able to use it.

**Comment by neehhaa06** [comment]
Hello @Octo8080X :)

fix: #2615

> Please follow this step.

```
Update importMap.json with correct mappings.

Add importMap to deno.json.

Verify imports in your files.

Use importMap in Deno commands.

Update Deno to the latest version.
```

**Comment by hoomp3** [comment]
is there actually a way to fix this? those steps do not work.

**Comment by ghost** [comment]
I'm also getting the same issue:
```
The manifest has been generated for 2 routes and 0 islands.
X [ERROR] specifier was a bare specifier, but was not remapped to anything by importMap. [plugin deno-resolver]

    https://deno.land/x/fresh@1.6.8/src/runtime/entrypoints/signals.ts:1:23:
      1 │ export { signal } from "@preact/signals";
        ╵                        ~~~~~~~~~~~~~~~~~

X [ERROR] specifier was a bare specifier, but was not remapped to anything by importMap. [plugin deno-resolver]

    https://deno.land/x/fresh@1.6.8/src/runtime/entrypoints/main.ts:13:7:
      13 │ } from "preact";
         ╵        ~~~~~~~~

error: Uncaught (in promise) Error: Build failed with 2 errors:
https://deno.land/x/fresh@1.6.8/src/runtime/entrypoints/main.ts:13:7: ERROR: [plugin: deno-resolver] specifier was a bare specifier, but was not remapped to anything by importMap.
https://deno.land/x/fresh@1.6.8/src/runtime/entrypoints/signals.ts:1:23: ERROR: [plugin: deno-resolver] specifier was a bare specifier, but was not remapped to anything by importMap.
  let error = new Error(text);
              ^
    at failureErrorWithLog (https://deno.land/x/esbuild@v0.20.2/mod.js:1626:15)
    at https://deno.land/x/esbuild@v0.20.2/mod.js:1034:25        
    at runOnEndCallbacks (https://deno.land/x/esbuild@v0.20.2/mod.js:1461:45)
    at buildResponseToResult (https://deno.land/x/esbuild@v0.20.2/mod.js:1032:7)
    at https://deno.land/x/esbuild@v0.20.2/mod.js:1061:16        
    at responseCallbacks.<computed> (https://deno.land/x/esbuild@v0.20.2/mod.js:679:9)
    at handleIncomingPacket (https://deno.land/x/esbuild@v0.20.2/mod.js:739:9)
    at readFromStdout (https://deno.land/x/esbuild@v0.20.2/mod.js:655:7)
    at https://deno.land/x/esbuild@v0.20.2/mod.js:1974:11        
    at eventLoopTick (ext:core/01_core.js:175:7)
 ```

**Comment by aditi-shah-st1** [comment]
Getting same error with Deno 2.0

**Comment by marvinhagemeister** [comment]
This is likely caused by a bug in Deno. See https://github.com/denoland/deno/issues/26138
