### ISSUE TITLE
No matching export for DENO_DEPLOYMENT_ID and setBuildId

### ISSUE THREAD

**Issue by TheMatten** [denoland/fresh#2644]
(At least) on `2.0.0-alpha.20`, trying to import something from `utils.ts` into an island results in following errors:

```
> deno task dev
Task dev deno run -A --watch=static/,routes/ dev.ts
Watcher Process started.

 🍋 Fresh ready   
    Local:  http://0.0.0.0:8001/

✘ [ERROR] No matching export in "fresh-internal:./runtime/build_id.ts" for import "DENO_DEPLOYMENT_ID"

    https://jsr.io/@fresh/core/2.0.0-alpha.20/src/build_cache.ts:3:9:
      3 │ import { DENO_DEPLOYMENT_ID, setBuildId } from "./runtime/build_id.ts";
        ╵          ~~~~~~~~~~~~~~~~~~

✘ [ERROR] No matching export in "fresh-internal:./runtime/build_id.ts" for import "setBuildId"

    https://jsr.io/@fresh/core/2.0.0-alpha.20/src/build_cache.ts:3:29:
      3 │ import { DENO_DEPLOYMENT_ID, setBuildId } from "./runtime/build_id.ts";
        ╵                              ~~~~~~~~~~

✘ [ERROR] No matching export in "fresh-internal:./runtime/build_id.ts" for import "DENO_DEPLOYMENT_ID"

    https://jsr.io/@fresh/core/2.0.0-alpha.20/src/app.ts:1:9:
      1 │ import { DENO_DEPLOYMENT_ID } from "./runtime/build_id.ts";
        ╵          ~~~~~~~~~~~~~~~~~~

error: Uncaught (in promise) Error: Build failed with 3 errors:
https://jsr.io/@fresh/core/2.0.0-alpha.20/src/app.ts:1:9: ERROR: No matching export in "fresh-internal:./runtime/build_id.ts" for import "DENO_DEPLOYMENT_ID"
https://jsr.io/@fresh/core/2.0.0-alpha.20/src/build_cache.ts:3:9: ERROR: No matching export in "fresh-internal:./runtime/build_id.ts" for import "DENO_DEPLOYMENT_ID"
https://jsr.io/@fresh/core/2.0.0-alpha.20/src/build_cache.ts:3:29: ERROR: No matching export in "fresh-internal:./runtime/build_id.ts" for import "setBuildId"
    at failureErrorWithLog (file:///home/[redacted]/.cache/deno/npm/registry.npmjs.org/esbuild/0.20.2/lib/main.js:1651:15)
    at file:///home/[redacted]/.cache/deno/npm/registry.npmjs.org/esbuild/0.20.2/lib/main.js:1059:25
    at runOnEndCallbacks (file:///home/[redacted]/.cache/deno/npm/registry.npmjs.org/esbuild/0.20.2/lib/main.js:1486:45)
    at buildResponseToResult (file:///home/[redacted]/.cache/deno/npm/registry.npmjs.org/esbuild/0.20.2/lib/main.js:1057:7)
    at file:///home/[redacted]/.cache/deno/npm/registry.npmjs.org/esbuild/0.20.2/lib/main.js:1086:16
    at responseCallbacks.<computed> (file:///home/[redacted]/.cache/deno/npm/registry.npmjs.org/esbuild/0.20.2/lib/main.js:704:9)
    at handleIncomingPacket (file:///home/[redacted]/.cache/deno/npm/registry.npmjs.org/esbuild/0.20.2/lib/main.js:764:9)
    at Readable.readFromStdout (file:///home/[redacted]/.cache/deno/npm/registry.npmjs.org/esbuild/0.20.2/lib/main.js:680:7)
    at Readable.emit (ext:deno_node/_stream.mjs:1851:9)
    at addChunk (ext:deno_node/_stream.mjs:2873:16)
Watcher Process failed. Restarting on file change...
```

Error seems to be related to `buildIdPlugin` in esbuild config, which doesn't generate these definitions when used: https://github.com/denoland/fresh/blob/b93ab3ad12491f251b3ab0f68044994305df42c3/src/dev/esbuild.ts#L181

Here is a simple reproduction from new Fresh template: https://git.sr.ht/~thematten/fresh_buildIdPlugin_repro (see `utils.ts` and `islands/Counter.tsx`)

**Comment by simlevesque** [comment]
This is still an issue in alpha 60.

**Comment by fry69** [comment]
Is that really a bug? I grant that the error message is a bit confusing.

The core of the problem is that the Island runs on the client browser, where environment variables from the server are not available.

I think I remember stumbling over this a while ago and reasoned that this is kind of expected when dealing with state from the server. Similar problems/situations occurred in other frameworks.

To fix this I ended up shoveling what I need on the browser into the application state object during app initialization (and more in other places). This state object is available on client browser.

See here -> https://github.com/fry69/orw/blob/fresh/orw-deno/utils.ts

**Comment by fry69** [comment]
Also it seems that is kind of error can get triggered through an outdated Fresh 2 (beta) version.

Please make double/triple sure you are on the latest released Fresh 2 version before adding a "me too" or complaining about this in the Discord.

**Comment by marvinhagemeister** [comment]
Closing as the underlying issue is resolved. If you run into this it means that you're on an old version of Fresh 2. Update to the latest version to resolve this issue.

**Comment by simlevesque** [comment]
@fry69 
> Please make double/triple sure you are on the latest released Fresh 2 version before adding a "me too" 

I was on the latest version at the time I wrote my comment. I wrote it on august 22nd, 2.0.0-alpha.60 was released on the 21st and 61 on the 25th.

So I'm not sure why you felt the need to say all this.  Maybe triple check yourself before commenting.

@marvinhagemeister Thank you and congrats on the release !

**Comment by fry69** [comment]
@simlevesque 

> So I'm not sure why you felt the need to say all this. Maybe triple check yourself before commenting.

This was meant for others reading this issue and complaining in the Discord citing it, sorry if that was not clear. This obviously happened today.
