### ISSUE TITLE
error when running the startup demo

### ISSUE THREAD

**Issue by i11010520** [denoland/fresh#2686]
create a demo: `deno run -A -r https://fresh.deno.dev`
running: `deno task start`

errors when opening or refreshing the page:
```
 🍋 Fresh ready 
    Local: http://localhost:8000/

An error occurred during route handling or page rendering.
An error occurred during route handling or page rendering.
An error occurred during route handling or page rendering.
An error occurred during route handling or page rendering.
Error: Invalid gzip data in archive: InvalidInput: invalid gzip header
    at extractFileFromTarGzip (https://deno.land/x/esbuild@v0.20.2/mod.js:1838:11)
    at installFromNPM (https://deno.land/x/esbuild@v0.20.2/mod.js:1790:22)
    at eventLoopTick (ext:core/01_core.js:175:7)
    at async install (https://deno.land/x/esbuild@v0.20.2/mod.js:1877:12)
    at async https://deno.land/x/esbuild@v0.20.2/mod.js:1948:23
    at async Module.initialize (https://deno.land/x/esbuild@v0.20.2/mod.js:1777:3)
    at async initializeEsbuild (https://deno.land/x/fresh@1.7.2/src/build/esbuild.ts:45:5)
    at async EsbuildBuilder.build (https://deno.land/x/fresh@1.7.2/src/build/esbuild.ts:61:21)
Error: Invalid gzip data in archive: InvalidInput: invalid gzip header
    at extractFileFromTarGzip (https://deno.land/x/esbuild@v0.20.2/mod.js:1838:11)
... 
[several same messages]
```

deno version:
```
deno 1.46.2 (stable, release, aarch64-apple-darwin)
v8 12.9.202.5-rusty
typescript 5.5.2
```

**Comment by i11010520** [comment]
maybe the root cause is npm registry
