### ISSUE TITLE
`Error: Objects are not valid as a child.` Conditional rendering. Multiple exports from island.

### ISSUE THREAD

**Issue by predaytor** [denoland/fresh#2687]
I need to check if the element has been hydrated (similar approach to react). When using a single island component import all works, but using multiple exports from an island component throws an error:

version: `jsr:@fresh/core@^2.0.0-alpha.22`
```bash
debug.js:348 Uncaught (in promise) Error: Objects are not valid as a child. Encountered an object with the keys {kind,name,id,__,__b,__i,__u,__d}.

  in div (at islands/Component.tsx:13)
  in ComponentPart

    at debug.js:348:12
    at Array.forEach (<anonymous>)
    at l.diffed (debug.js:345:20)
    at index.ts:219:2
    at O (index.js:311:30)
    at S (children.js:79:3)
    at O (index.js:246:4)
    at P (component.js:134:3)
```
`hooks/use-is-hydrated.ts`:
```ts
import { useEffect, useState } from 'preact/hooks';

export const useIsHydrated = () => {
	const [isHydrated, setIsHydrated] = useState(false);

	useEffect(() => {
		setIsHydrated(true);
	}, []);

	return isHydrated;
};
```

Single export (`islands/Counter.tsx` from example):
```tsx
import type { Signal } from "@preact/signals";
import { Button } from "../components/Button.tsx";
import { useIsHydrated } from "../hooks/use-is-hydrated.ts";

interface CounterProps {
  count: Signal<number>;
}

export default function Counter(props: CounterProps) {
  const isHydrated = useIsHydrated();

  if (!isHydrated) return <></>;

  return (
    <div class="flex gap-8 py-6">
      <Button onClick={() => props.count.value -= 1}>-1</Button>
      <p class="text-3xl tabular-nums">{props.count}</p>
      <Button onClick={() => props.count.value += 1}>+1</Button>
    </div>
  );
}
```

Multiple exports (`islands/Test.tsx`):
```tsx
import { ComponentChildren } from "preact";
import { useIsHydrated } from "../hooks/use-is-hydrated.ts";

export function Component(props: { children?: ComponentChildren }) {
  return <div>{props.children}</div>;
}

export function ComponentPart(props: { children?: ComponentChildren }) {
  const isHydrated = useIsHydrated();

  if (!isHydrated) return <></>;

  return <div>{props.children}</div>;
}
```
Usage (`/routes/index.tsx`):
```tsx
import { useSignal } from "@preact/signals";
import { define } from "../utils.ts";
import Counter from "../islands/Counter.tsx";
import { Component, ComponentPart } from "../islands/Component.tsx";

export default define.page(function Home() {
  const count = useSignal(3);

  return (
    <div class="px-4 py-8 mx-auto fresh-gradient">
      <div class="max-w-screen-md mx-auto flex flex-col items-center justify-center">
        <img
          class="my-6"
          src="/logo.svg"
          width="128"
          height="128"
          alt="the Fresh logo: a sliced lemon dripping with juice"
        />
        <h1 class="text-4xl font-bold">Welcome to Fresh</h1>
        <p class="my-4">
          Try updating this message in the
          <code class="mx-2">./routes/index.tsx</code> file, and refresh.
        </p>
        <Counter count={count} />

        <Component>
          <ComponentPart>Part</ComponentPart>
        </Component>
      </div>
    </div>
  );
});
```

**Comment by bartlomieju** [comment]
I tested this against the current Fresh 2 release and the server-rendered HTML, island serialization, and boot script all look correct:

- Multiple named exports from a single island file are properly imported
- Nested islands (`ComponentPart` inside `Component`) use the slot system correctly
- Children are serialized into `<template>` elements and referenced via slot IDs

This was reported against `alpha.22` — there have been significant hydration fixes since then. Could you verify if this is still an issue on the current release?
