### ISSUE TITLE
Default imports for some modules behave differently when statically imported on client side vs server side

### ISSUE THREAD

**Issue by lionel-rowe** [denoland/fresh#2696]
Default imports for some modules, such as `npm:prettier@3.3.3/parser-html`, behave differently when statically imported on the client side vs server side.

Repro:

1. Bootstrap app with `deno run -A -r https://fresh.deno.dev`
2. Replace content of `islands/Counter.tsx` with the following: 

   ```ts
   import * as staticMod from 'npm:prettier@3.3.3/parser-html'
   import { assert } from "jsr:@std/assert@1.0.6";
   
   const dynamicMod = await import('npm:prettier@3.3.3/parser-html')
   
   assert('default' in dynamicMod, 'No default prop (dynamic)!')
   console.log('ok (dynamic)')
   
   assert('default' in staticMod, 'No default prop! (static)')
   console.log('ok (static)')
   
   export default function() {
     return <div>...</div>
   }
   ```

3. Observe output in CLI console:
   ```
   ok (dynamic)
   ok (static)
   ```

4. Open server URL and observe output in browser console:
   ```
   ok (dynamic)
   assert.ts:21 Uncaught AssertionError: No default prop! (static)
       at assert (assert.ts:21:11)
       at Counter.tsx:9:1
   ```

On the server, both `staticMod` and `dynamicMod` are module objects with `default` props; however, on the client, `staticMod` is itself the `default` export (i.e. it doesn't have a `default` prop of its own).

**Comment by bartlomieju** [comment]
This was a Fresh 1.x issue caused by esbuild's client-side bundling handling CJS default exports differently from Deno's server-side resolution.

In Fresh 2 with Vite, both static and dynamic imports behave consistently on the server side. Vite's module handling is fundamentally different from esbuild's and handles CJS/ESM interop more consistently across client and server.

Tested with `prettier/parser-html` on Fresh 2.2.x — both `import * as mod` and `await import()` produce consistent module objects with `default` properties on the server. Closing as resolved by the Fresh 2 architecture change.

If anyone still encounters this specific discrepancy on Fresh 2, please open a new issue with a reproduction.
