### ISSUE TITLE
Error at tailwind config

### ISSUE THREAD

**Issue by rempas** [denoland/fresh#2705]
I'm following the [page](https://fresh.deno.dev/docs/examples/migrating-to-tailwind) and when I try to launch the server (with `deno task start`), I'm getting the following error:

```
error: Uncaught (in promise) TypeError: The module's source code could not be parsed: Expected ',', got 'Config' at file:///home/rempas/Projects/Programming/PersonalPage/tailwind.config.js:1:15

  import { type Config } from "tailwindcss";
                ~~~~~~
  const tailwindConfig = (await import(url)).default as Config;
                          ^
    at async Module.initTailwind (https://deno.land/x/fresh@1.7.2/plugins/tailwind/compiler.ts:48:27)
    at async initTailwind (https://deno.land/x/fresh@1.7.2/plugins/tailwind.ts:11:10)
    at async Object.configResolved (https://deno.land/x/fresh@1.7.2/plugins/tailwind.ts:91:21)
    at async Promise.all (index 0)
    at async getServerContext (https://deno.land/x/fresh@1.7.2/src/server/context.ts:79:5)
    at async dev (https://deno.land/x/fresh@1.7.2/src/dev/dev_command.ts:57:17)
    at async file:///home/rempas/Projects/Programming/PersonalPage/dev.ts:8:1
```

**Comment by rschristian** [comment]
Is your config file JS or TS? The error seems to indicate the former. Type imports are TS-only.

**Comment by rempas** [comment]
> Is your config file JS or TS? The error seems to indicate the former. Type imports are TS-only.

I had first followed the [tailwind docs](https://tailwindcss.com/docs/installation) and I had a ".js" file and didn't even notice that :facepalm: 

Thanks a lot and have a beautiful day!
