### ISSUE TITLE
Using daisy ui throws an error

### ISSUE THREAD

**Issue by FatahChan** [denoland/fresh#2723]
When using [daisyui](https://daisyui.com/docs/install/) as a tailwind plugin will throw an error

Reproduction
1. `deno run -A -r https://fresh.deno.dev`
2. make sure to choose tailwind
3. `deno add npm:daisyui`
4. add daisyui to tailwind config
5. deno task start
6. open the webpage

```ts
// tailwind.config.ts
import { type Config } from "tailwindcss/Config";
import daisyui from "daisyui";
export default {
  content: [
    "routes/**/*.{ts,tsx}",
    "components/**/*.{ts,tsx}",
    "islands/**/*.{ts,tsx}",
  ],
  Plugins: [daisyui],
} satisfies Config;
```

Throws the following error

```
CssSyntaxError: <css input>:1:1: The `border-border` class does not exist. If `border-border` is a custom class, make sure it is defined within a `@layer` directive.
    at Input.error (file:///E:/Dev/fresh-start/node_modules/.deno/postcss@8.4.35/node_modules/postcss/lib/input.js:106:16)
    at AtRule.error (file:///E:/Dev/fresh-start/node_modules/.deno/postcss@8.4.35/node_modules/postcss/lib/node.js:115:32)
    at processApply (file:///E:/Dev/fresh-start/node_modules/.deno/tailwindcss@3.4.1/node_modules/tailwindcss/lib/lib/expandApplyAtRules.js:380:29)
    at file:///E:/Dev/fresh-start/node_modules/.deno/tailwindcss@3.4.1/node_modules/tailwindcss/lib/lib/expandApplyAtRules.js:538:9
    at file:///E:/Dev/fresh-start/node_modules/.deno/tailwindcss@3.4.1/node_modules/tailwindcss/lib/processTailwindFeatures.js:57:50
    at eventLoopTick (ext:core/01_core.js:175:7)
    at async plugins (file:///E:/Dev/fresh-start/node_modules/.deno/tailwindcss@3.4.1/node_modules/tailwindcss/lib/plugin.js:38:17)
    at async LazyResult.runAsync (file:///E:/Dev/fresh-start/node_modules/.deno/postcss@8.4.35/node_modules/postcss/lib/lazy-result.js:261:11)
    at async handler (https://deno.land/x/fresh@1.7.3/plugins/tailwind.ts:49:25)
    at async handler (https://deno.land/x/fresh@1.7.3/src/server/context.ts:295:14) {
  name: "CssSyntaxError",
  reason: "The `border-border` class does not exist. If `border-border` is a custom class, make sure it is defined within a `@layer` directive.",
  source: "@tailwind base;\n" +
    "@tailwind components;\n" +
    "@tailwind utilities;\n" +
    "\n" +
    "@layer base {\n" +
    "  :root {\n" +
    "    --background: 0 0% 100%;\n" +
    "    --foreground: 222.2 47.4% 11.2%;\n" +
    "\n" +
    "    --muted: 210 40% 96.1%;\n" +
    "    --muted-foreground: 215.4 16.3% 46.9%;\n" +
    "\n" +
    "    --popover: 0 0% 100%;\n" +
    "    --popover-foreground: 222.2 47.4% 11.2%;\n" +
    "\n" +
    "    --border: 214.3 31.8% 91.4%;\n" +
    "    --input: 214.3 31.8% 91.4%;\n" +
    "\n" +
    "    --card: 0 0% 100%;\n" +
    "    --card-foreground: 222.2 47.4% 11.2%;\n" +
    "\n" +
    "    --primary: 222.2 47.4% 11.2%;\n" +
    "    --primary-foreground: 210 40% 98%;\n" +
    "\n" +
    "    --secondary: 210 40% 96.1%;\n" +
    "    --secondary-foreground: 222.2 47.4% 11.2%;\n" +
    "\n" +
    "    --accent: 210 40% 96.1%;\n" +
    "    --accent-foreground: 222.2 47.4% 11.2%;\n" +
    "\n" +
    "    --destructive: 0 100% 50%;\n" +
    "    --destructive-foreground: 210 40% 98%;\n" +
    "\n" +
    "    --ring: 215 20.2% 65.1%;\n" +
    "\n" +
    "    --radius: 0.5rem;\n" +
    "  }\n" +
    "\n" +
    "  .dark {\n" +
    "    --background: 224 71% 4%;\n" +
    "    --foreground: 213 31% 91%;\n" +
    "\n" +
    "    --muted: 223 47% 11%;\n" +
    "    --muted-foreground: 215.4 16.3% 56.9%;\n" +
    "\n" +
    "    --accent: 216 34% 17%;\n" +
    "    --accent-foreground: 210 40% 98%;\n" +
    "\n" +
    "    --popover: 224 71% 4%;\n" +
    "    --popover-foreground: 215 20.2% 65.1%;\n" +
    "\n" +
    "    --border: 216 34% 17%;\n" +
    "    --input: 216 34% 17%;\n" +
    "\n" +
    "    --card: 224 71% 4%;\n" +
    "    --card-foreground: 213 31% 91%;\n" +
    "\n" +
    "    --primary: 210 40% 98%;\n" +
    "    --primary-foreground: 222.2 47.4% 1.2%;\n" +
    "\n" +
    "    --secondary: 222.2 47.4% 11.2%;\n" +
    "    --secondary-foreground: 210 40% 98%;\n" +
    "\n" +
    "    --destructive: 0 63% 31%;\n" +
    "    --destructive-foreground: 210 40% 98%;\n" +
    "\n" +
    "    --ring: 216 34% 17%;\n" +
    "\n" +
    "    --radius: 0.5rem;\n" +
    "  }\n" +
    "}\n" +
    "\n" +
    "@layer base {\n" +
    "  * {\n" +
    "    @apply border-border;\n" +
    "  }\n" +
    "  body {\n" +
    "    @apply bg-background text-foreground;\n" +
    '    font-feature-settings: "rlig" 1, "calt" 1;\n' +
    "  }\n" +
    "}\n",
  line: 1,
  column: 1,
  endLine: 1,
  endColumn: 16,
  input: {
    column: 1,
    endColumn: 16,
    endLine: 1,
    line: 1,
    source: "@tailwind base;\n" +
      "@tailwind components;\n" +
      "@tailwind utilities;\n" +
      "\n" +
      "@layer base {\n" +
      "  :root {\n" +
      "    --background: 0 0% 100%;\n" +
      "    --foreground: 222.2 47.4% 11.2%;\n" +
      "\n" +
      "    --muted: 210 40% 96.1%;\n" +
      "    --muted-foreground: 215.4 16.3% 46.9%;\n" +
      "\n" +
      "    --popover: 0 0% 100%;\n" +
      "    --popover-foreground: 222.2 47.4% 11.2%;\n" +
      "\n" +
      "    --border: 214.3 31.8% 91.4%;\n" +
      "    --input: 214.3 31.8% 91.4%;\n" +
      "\n" +
      "    --card: 0 0% 100%;\n" +
      "    --card-foreground: 222.2 47.4% 11.2%;\n" +
      "\n" +
      "    --primary: 222.2 47.4% 11.2%;\n" +
      "    --primary-foreground: 210 40% 98%;\n" +
      "\n" +
      "    --secondary: 210 40% 96.1%;\n" +
      "    --secondary-foreground: 222.2 47.4% 11.2%;\n" +
      "\n" +
      "    --accent: 210 40% 96.1%;\n" +
      "    --accent-foreground: 222.2 47.4% 11.2%;\n" +
      "\n" +
      "    --destructive: 0 100% 50%;\n" +
      "    --destructive-foreground: 210 40% 98%;\n" +
      "\n" +
      "    --ring: 215 20.2% 65.1%;\n" +
      "\n" +
      "    --radius: 0.5rem;\n" +
      "  }\n" +
      "\n" +
      "  .dark {\n" +
      "    --background: 224 71% 4%;\n" +
      "    --foreground: 213 31% 91%;\n" +
      "\n" +
      "    --muted: 223 47% 11%;\n" +
      "    --muted-foreground: 215.4 16.3% 56.9%;\n" +
      "\n" +
      "    --accent: 216 34% 17%;\n" +
      "    --accent-foreground: 210 40% 98%;\n" +
      "\n" +
      "    --popover: 224 71% 4%;\n" +
      "    --popover-foreground: 215 20.2% 65.1%;\n" +
      "\n" +
      "    --border: 216 34% 17%;\n" +
      "    --input: 216 34% 17%;\n" +
      "\n" +
      "    --card: 224 71% 4%;\n" +
      "    --card-foreground: 213 31% 91%;\n" +
      "\n" +
      "    --primary: 210 40% 98%;\n" +
      "    --primary-foreground: 222.2 47.4% 1.2%;\n" +
      "\n" +
      "    --secondary: 222.2 47.4% 11.2%;\n" +
      "    --secondary-foreground: 210 40% 98%;\n" +
      "\n" +
      "    --destructive: 0 63% 31%;\n" +
      "    --destructive-foreground: 210 40% 98%;\n" +
      "\n" +
      "    --ring: 216 34% 17%;\n" +
      "\n" +
      "    --radius: 0.5rem;\n" +
      "  }\n" +
      "}\n" +
      "\n" +
      "@layer base {\n" +
      "  * {\n" +
      "    @apply border-border;\n" +
      "  }\n" +
      "  body {\n" +
      "    @apply bg-background text-foreground;\n" +
      '    font-feature-settings: "rlig" 1, "calt" 1;\n' +
      "  }\n" +
      "}\n"
  },
  plugin: undefined
}
```

Edit:

I have already tested using daisy ui with vite + preact works fine

**Comment by FatahChan** [comment]
https://stackoverflow.com/questions/77443221/the-border-border-class-does-not-exist-if-border-border-is-a-custom-class

issue seems like something to do with extension, not sure how
