### ISSUE TITLE
Islands import. `Could not find chunk for`

### ISSUE THREAD

**Issue by predaytor** [denoland/fresh#2761]
When using this type of export, sometimes throws an error when running in production (fly.io, Docker build). Cannot to reproduce locally.

`islands/carousel/index.tsx`:
```tsx
import {
	CarouselButton as Button,
	CarouselContent as Content,
	CarouselControls as Controls,
	CarouselRoot as Root,
	CarouselScroller as Scroller,
	CarouselSlide as Slide,
	CarouselTitle as Title,
} from './carousel.tsx';

export type {
	CarouselButtonProps,
	CarouselContentProps,
	CarouselControlsProps,
	CarouselRootProps,
	CarouselScrollerProps,
	CarouselSlideProps,
	CarouselTitleProps,
} from './carousel.tsx';

export const Carousel = Object.assign(Root, { Title, Controls, Button, Content, Scroller, Slide });
```
```tsx
<Carousel>
	<Carousel.Scroller>
		<Carousel.Content>
			{project.coverGallery.gallery.nodes.map((slide, slideIdx) => {
				return <Carousel.Slide key={slide.id}></Carousel.Slide>;
			})}
		</Carousel.Content>
	</Carousel.Scroller>
</Carousel>
```
Logs:
```console
2024-11-13T19:15:03Z app[287133dc001028] ams [info]Error: Could not find chunk for CarouselRoot /app/islands/carousel/carousel.tsx#CarouselRoot
2024-11-13T19:15:03Z app[287133dc001028] ams [info]    at https://jsr.io/@fresh/core/2.0.0-alpha.25/src/runtime/server/preact_hooks.tsx:463:15
2024-11-13T19:15:03Z app[287133dc001028] ams [info]    at Array.map (<anonymous>)
2024-11-13T19:15:03Z app[287133dc001028] ams [info]    at Object.FreshRuntimeScript (https://jsr.io/@fresh/core/2.0.0-alpha.25/src/runtime/server/preact_hooks.tsx:460:37)
```
https://jsr.io/@fresh/core/2.0.0-alpha.25/src/runtime/server/preact_hooks.tsx#L463

**Comment by predaytor** [comment]
Maybe it has to do with reexport from index file, only then this issue occurs.

works:
```ts
import { CarouselRoot } from '~/islands/carousel/carousel.tsx';
```
breaks:
```ts
import { CarouselRoot } from '~/islands/carousel/index.tsx';
```

**Comment by marvinhagemeister** [comment]
Resolved by https://github.com/denoland/fresh/pull/3122
