### ISSUE TITLE
dynamic import within Island components with `useEffect`

### ISSUE THREAD

**Issue by HeavySnowJakarta** [denoland/fresh#2775]
I was trying to include Monaco editor and related tree-sitter libraries into Fresh pages. Here's my codes:

```tsx
// Initialize the editor, run CSR-only after the DOM is loaded.

import { useEffect } from "preact/hooks";

// tree-sitter-related JSON configurations.

export default function Init() {

    useEffect(() => {
        (async ()=>{
            // TODO: Should be enabled in the future.
            // const {initEditor} = await import("../static/editor.js");
            // initEditor();

            console.log("Initializing the editor")

            // Import Monaco editor.
            const monaco = await import("https://esm.sh/monaco-editor@0.52.0")

            // // Import tree-sitter-related libraries.
            // const treeSitterCppResponse = await fetch("/assets/tree-sitter-cpp.wasm")
            // const treeSitterCpp = await WebAssembly.instantiateStreaming(
            //     treeSitterCppResponse,
            //     {}
            // );
            // const Parser = await import("https://esm.sh/web-tree-sitter@0.24.4")
            // const {Theme, Language, MonacoTreeSitter} = await import("https://esm.sh/monaco-tree-sitter@0.0.5")
            // const cppGrammarResponse = await fetch("../static/assets/tree-sitter-grammar/cpp.json")
            // const cppGrammar = cppGrammarResponse.json()
            // const themeResponse = await fetch("../static/assets/tree-sitter-theme/tomorrow.json")
            // const theme = await themeResponse.json()

            // // Initialize the tree-sitter libraries.
            // Theme.load(theme);
            // console.log("Here is the structure of Parser:");
            // console.log(Parser);
            // // await Parser.default.init()
            // // const language = new Language(cppGrammar)

            // (globalThis as typeof globalThis & {monaco: typeof monaco})
            //     .monaco = monaco;
        })();
    }, [])

    return <></>
}
```

The most codes have been commented for the following errors, but the codes above still causes the errors (as well as warnings):

```
▲ [WARNING] The "??" operator here will always return the right operand [suspicious-nullish-coalescing]

    https://esm.sh/v135/monaco-editor@0.52.0/denonext/monaco-editor.mjs:668:60979:
      668 │ ...ginal,e.modified),u=(e.original,e.modified,void 0)??u,u=(e.original,e.modified,void 0)??u,Yt(g=>{r(u,...
          ╵                                                      ~~

  The left operand of the "??" operator here will always be null or undefined, so it will never be
  returned. This usually indicates a bug in your code:

    https://esm.sh/v135/monaco-editor@0.52.0/denonext/monaco-editor.mjs:668:60950:
      668 │ ...|(u=g0e(u,e.original,e.modified),u=(e.original,e.modified,void 0)??u,u=(e.original,e.modified,void 0)...
          ╵                                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

▲ [WARNING] The "??" operator here will always return the right operand [suspicious-nullish-coalescing]

    https://esm.sh/v135/monaco-editor@0.52.0/denonext/monaco-editor.mjs:668:61015:
      668 │ ...dified,void 0)??u,u=(e.original,e.modified,void 0)??u,Yt(g=>{r(u,g),this._lastDiff=u;let m=ek.fromDif...
          ╵                                                      ~~

  The left operand of the "??" operator here will always be null or undefined, so it will never be
  returned. This usually indicates a bug in your code:

    https://esm.sh/v135/monaco-editor@0.52.0/denonext/monaco-editor.mjs:668:60986:
      668 │ ...e.original,e.modified,void 0)??u,u=(e.original,e.modified,void 0)??u,Yt(g=>{r(u,g),this._lastDiff=u;l...
          ╵                                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

▲ [WARNING] The "??" operator here will always return the right operand [suspicious-nullish-coalescing]

    https://esm.sh/v135/monaco-editor@0.52.0/denonext/esm/vs/basic-languages/freemarker2/freemarker2.js:668:66289:
      668 │ ...ginal,e.modified),u=(e.original,e.modified,void 0)??u,u=(e.original,e.modified,void 0)??u,wt(f=>{r(u,...
          ╵                                                      ~~

  The left operand of the "??" operator here will always be null or undefined, so it will never be
  returned. This usually indicates a bug in your code:

    https://esm.sh/v135/monaco-editor@0.52.0/denonext/esm/vs/basic-languages/freemarker2/freemarker2.js:668:66260:
      668 │ ...||(u=wQ(u,e.original,e.modified),u=(e.original,e.modified,void 0)??u,u=(e.original,e.modified,void 0)...
          ╵                                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

▲ [WARNING] The "??" operator here will always return the right operand [suspicious-nullish-coalescing]

    https://esm.sh/v135/monaco-editor@0.52.0/denonext/esm/vs/basic-languages/freemarker2/freemarker2.js:668:66325:
      668 │ ...dified,void 0)??u,u=(e.original,e.modified,void 0)??u,wt(f=>{r(u,f),this._lastDiff=u;let g=$b.fromDif...
          ╵                                                      ~~

  The left operand of the "??" operator here will always be null or undefined, so it will never be
  returned. This usually indicates a bug in your code:

    https://esm.sh/v135/monaco-editor@0.52.0/denonext/esm/vs/basic-languages/freemarker2/freemarker2.js:668:66296:
      668 │ ...e.original,e.modified,void 0)??u,u=(e.original,e.modified,void 0)??u,wt(f=>{r(u,f),this._lastDiff=u;l...
          ╵                                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

▲ [WARNING] The "??" operator here will always return the right operand [suspicious-nullish-coalescing]

    https://esm.sh/v135/monaco-editor@0.52.0/denonext/esm/vs/basic-languages/handlebars/handlebars.js:668:66289:
      668 │ ...ginal,e.modified),u=(e.original,e.modified,void 0)??u,u=(e.original,e.modified,void 0)??u,wt(f=>{r(u,...
          ╵                                                      ~~

  The left operand of the "??" operator here will always be null or undefined, so it will never be
  returned. This usually indicates a bug in your code:

    https://esm.sh/v135/monaco-editor@0.52.0/denonext/esm/vs/basic-languages/handlebars/handlebars.js:668:66260:
      668 │ ...||(u=hQ(u,e.original,e.modified),u=(e.original,e.modified,void 0)??u,u=(e.original,e.modified,void 0)...
          ╵                                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

▲ [WARNING] The "??" operator here will always return the right operand [suspicious-nullish-coalescing]

    https://esm.sh/v135/monaco-editor@0.52.0/denonext/esm/vs/basic-languages/handlebars/handlebars.js:668:66325:
      668 │ ...dified,void 0)??u,u=(e.original,e.modified,void 0)??u,wt(f=>{r(u,f),this._lastDiff=u;let g=Ub.fromDif...
          ╵                                                      ~~

  The left operand of the "??" operator here will always be null or undefined, so it will never be
  returned. This usually indicates a bug in your code:

    https://esm.sh/v135/monaco-editor@0.52.0/denonext/esm/vs/basic-languages/handlebars/handlebars.js:668:66296:
      668 │ ...e.original,e.modified,void 0)??u,u=(e.original,e.modified,void 0)??u,wt(f=>{r(u,f),this._lastDiff=u;l...
          ╵                                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

▲ [WARNING] The "??" operator here will always return the right operand [suspicious-nullish-coalescing]

    https://esm.sh/v135/monaco-editor@0.52.0/denonext/esm/vs/language/html/htmlMode.js:668:66289:
      668 │ ...ginal,e.modified),u=(e.original,e.modified,void 0)??u,u=(e.original,e.modified,void 0)??u,yt(f=>{r(u,...
          ╵                                                      ~~

  The left operand of the "??" operator here will always be null or undefined, so it will never be
  returned. This usually indicates a bug in your code:

    https://esm.sh/v135/monaco-editor@0.52.0/denonext/esm/vs/language/html/htmlMode.js:668:66260:
      668 │ ...||(u=oJ(u,e.original,e.modified),u=(e.original,e.modified,void 0)??u,u=(e.original,e.modified,void 0)...
          ╵                                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

▲ [WARNING] The "??" operator here will always return the right operand [suspicious-nullish-coalescing]

    https://esm.sh/v135/monaco-editor@0.52.0/denonext/esm/vs/language/html/htmlMode.js:668:66325:
      668 │ ...dified,void 0)??u,u=(e.original,e.modified,void 0)??u,yt(f=>{r(u,f),this._lastDiff=u;let g=t1.fromDif...
          ╵                                                      ~~

  The left operand of the "??" operator here will always be null or undefined, so it will never be
  returned. This usually indicates a bug in your code:

    https://esm.sh/v135/monaco-editor@0.52.0/denonext/esm/vs/language/html/htmlMode.js:668:66296:
      668 │ ...e.original,e.modified,void 0)??u,u=(e.original,e.modified,void 0)??u,yt(f=>{r(u,f),this._lastDiff=u;l...
          ╵                                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

▲ [WARNING] The "??" operator here will always return the right operand [suspicious-nullish-coalescing]

    https://esm.sh/v135/monaco-editor@0.52.0/denonext/esm/vs/basic-languages/xml/xml.js:668:66289:
      668 │ ...ginal,e.modified),u=(e.original,e.modified,void 0)??u,u=(e.original,e.modified,void 0)??u,wt(f=>{r(u,...
          ╵                                                      ~~

  The left operand of the "??" operator here will always be null or undefined, so it will never be
  returned. This usually indicates a bug in your code:

    https://esm.sh/v135/monaco-editor@0.52.0/denonext/esm/vs/basic-languages/xml/xml.js:668:66260:
      668 │ ...||(u=dQ(u,e.original,e.modified),u=(e.original,e.modified,void 0)??u,u=(e.original,e.modified,void 0)...
          ╵                                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

▲ [WARNING] The "??" operator here will always return the right operand [suspicious-nullish-coalescing]

    https://esm.sh/v135/monaco-editor@0.52.0/denonext/esm/vs/basic-languages/xml/xml.js:668:66325:
      668 │ ...dified,void 0)??u,u=(e.original,e.modified,void 0)??u,wt(f=>{r(u,f),this._lastDiff=u;let g=Ub.fromDif...
          ╵                                                      ~~

  The left operand of the "??" operator here will always be null or undefined, so it will never be
  returned. This usually indicates a bug in your code:

    https://esm.sh/v135/monaco-editor@0.52.0/denonext/esm/vs/basic-languages/xml/xml.js:668:66296:
      668 │ ...e.original,e.modified,void 0)??u,u=(e.original,e.modified,void 0)??u,wt(f=>{r(u,f),this._lastDiff=u;l...
          ╵                                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

▲ [WARNING] The "??" operator here will always return the right operand [suspicious-nullish-coalescing]

    https://esm.sh/v135/monaco-editor@0.52.0/denonext/esm/vs/basic-languages/yaml/yaml.js:668:66289:
      668 │ ...ginal,e.modified),u=(e.original,e.modified,void 0)??u,u=(e.original,e.modified,void 0)??u,wt(f=>{r(u,...
          ╵                                                      ~~

  The left operand of the "??" operator here will always be null or undefined, so it will never be
  returned. This usually indicates a bug in your code:

    https://esm.sh/v135/monaco-editor@0.52.0/denonext/esm/vs/basic-languages/yaml/yaml.js:668:66260:
      668 │ ...||(u=dQ(u,e.original,e.modified),u=(e.original,e.modified,void 0)??u,u=(e.original,e.modified,void 0)...
          ╵                                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

▲ [WARNING] The "??" operator here will always return the right operand [suspicious-nullish-coalescing]

    https://esm.sh/v135/monaco-editor@0.52.0/denonext/esm/vs/basic-languages/html/html.js:668:66289:
      668 │ ...ginal,e.modified),u=(e.original,e.modified,void 0)??u,u=(e.original,e.modified,void 0)??u,wt(f=>{r(u,...
          ╵                                                      ~~

  The left operand of the "??" operator here will always be null or undefined, so it will never be
  returned. This usually indicates a bug in your code:

    https://esm.sh/v135/monaco-editor@0.52.0/denonext/esm/vs/basic-languages/html/html.js:668:66260:
      668 │ ...||(u=hQ(u,e.original,e.modified),u=(e.original,e.modified,void 0)??u,u=(e.original,e.modified,void 0)...
          ╵                                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

▲ [WARNING] The "??" operator here will always return the right operand [suspicious-nullish-coalescing]

    https://esm.sh/v135/monaco-editor@0.52.0/denonext/esm/vs/basic-languages/html/html.js:668:66325:
      668 │ ...dified,void 0)??u,u=(e.original,e.modified,void 0)??u,wt(f=>{r(u,f),this._lastDiff=u;let g=Ub.fromDif...
          ╵                                                      ~~

  The left operand of the "??" operator here will always be null or undefined, so it will never be
  returned. This usually indicates a bug in your code:

    https://esm.sh/v135/monaco-editor@0.52.0/denonext/esm/vs/basic-languages/html/html.js:668:66296:
      668 │ ...e.original,e.modified,void 0)??u,u=(e.original,e.modified,void 0)??u,wt(f=>{r(u,f),this._lastDiff=u;l...
          ╵                                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

▲ [WARNING] The "??" operator here will always return the right operand [suspicious-nullish-coalescing]

    https://esm.sh/v135/monaco-editor@0.52.0/denonext/esm/vs/basic-languages/yaml/yaml.js:668:66325:
      668 │ ...dified,void 0)??u,u=(e.original,e.modified,void 0)??u,wt(f=>{r(u,f),this._lastDiff=u;let g=Ub.fromDif...
          ╵                                                      ~~

  The left operand of the "??" operator here will always be null or undefined, so it will never be
  returned. This usually indicates a bug in your code:

    https://esm.sh/v135/monaco-editor@0.52.0/denonext/esm/vs/basic-languages/yaml/yaml.js:668:66296:
      668 │ ...e.original,e.modified,void 0)??u,u=(e.original,e.modified,void 0)??u,wt(f=>{r(u,f),this._lastDiff=u;l...
          ╵                                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

▲ [WARNING] The "??" operator here will always return the right operand [suspicious-nullish-coalescing]

    https://esm.sh/v135/monaco-editor@0.52.0/denonext/esm/vs/basic-languages/liquid/liquid.js:668:66289:
      668 │ ...ginal,e.modified),u=(e.original,e.modified,void 0)??u,u=(e.original,e.modified,void 0)??u,wt(f=>{r(u,...
          ╵                                                      ~~

  The left operand of the "??" operator here will always be null or undefined, so it will never be
  returned. This usually indicates a bug in your code:

    https://esm.sh/v135/monaco-editor@0.52.0/denonext/esm/vs/basic-languages/liquid/liquid.js:668:66260:
      668 │ ...||(u=hQ(u,e.original,e.modified),u=(e.original,e.modified,void 0)??u,u=(e.original,e.modified,void 0)...
          ╵                                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

▲ [WARNING] The "??" operator here will always return the right operand [suspicious-nullish-coalescing]

    https://esm.sh/v135/monaco-editor@0.52.0/denonext/esm/vs/basic-languages/liquid/liquid.js:668:66325:
      668 │ ...dified,void 0)??u,u=(e.original,e.modified,void 0)??u,wt(f=>{r(u,f),this._lastDiff=u;let g=Ub.fromDif...
          ╵                                                      ~~

  The left operand of the "??" operator here will always be null or undefined, so it will never be
  returned. This usually indicates a bug in your code:

    https://esm.sh/v135/monaco-editor@0.52.0/denonext/esm/vs/basic-languages/liquid/liquid.js:668:66296:
      668 │ ...e.original,e.modified,void 0)??u,u=(e.original,e.modified,void 0)??u,wt(f=>{r(u,f),this._lastDiff=u;l...
          ╵                                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

▲ [WARNING] The "??" operator here will always return the right operand [suspicious-nullish-coalescing]

    https://esm.sh/v135/monaco-editor@0.52.0/denonext/esm/vs/basic-languages/mdx/mdx.js:668:66289:
      668 │ ...ginal,e.modified),u=(e.original,e.modified,void 0)??u,u=(e.original,e.modified,void 0)??u,wt(f=>{r(u,...
          ╵                                                      ~~

  The left operand of the "??" operator here will always be null or undefined, so it will never be
  returned. This usually indicates a bug in your code:

    https://esm.sh/v135/monaco-editor@0.52.0/denonext/esm/vs/basic-languages/mdx/mdx.js:668:66260:
      668 │ ...||(u=dQ(u,e.original,e.modified),u=(e.original,e.modified,void 0)??u,u=(e.original,e.modified,void 0)...
          ╵                                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

▲ [WARNING] The "??" operator here will always return the right operand [suspicious-nullish-coalescing]

    https://esm.sh/v135/monaco-editor@0.52.0/denonext/esm/vs/basic-languages/mdx/mdx.js:668:66325:
      668 │ ...dified,void 0)??u,u=(e.original,e.modified,void 0)??u,wt(f=>{r(u,f),this._lastDiff=u;let g=$b.fromDif...
          ╵                                                      ~~

  The left operand of the "??" operator here will always be null or undefined, so it will never be
  returned. This usually indicates a bug in your code:

    https://esm.sh/v135/monaco-editor@0.52.0/denonext/esm/vs/basic-languages/mdx/mdx.js:668:66296:
      668 │ ...e.original,e.modified,void 0)??u,u=(e.original,e.modified,void 0)??u,wt(f=>{r(u,f),this._lastDiff=u;l...
          ╵                                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

▲ [WARNING] The "??" operator here will always return the right operand [suspicious-nullish-coalescing]

    https://esm.sh/v135/monaco-editor@0.52.0/denonext/esm/vs/language/typescript/tsMode.js:668:67385:
      668 │ ...ginal,e.modified),u=(e.original,e.modified,void 0)??u,u=(e.original,e.modified,void 0)??u,Pt(f=>{r(u,...
          ╵                                                      ~~

  The left operand of the "??" operator here will always be null or undefined, so it will never be
  returned. This usually indicates a bug in your code:

    https://esm.sh/v135/monaco-editor@0.52.0/denonext/esm/vs/language/typescript/tsMode.js:668:67356:
      668 │ ...|(u=Wle(u,e.original,e.modified),u=(e.original,e.modified,void 0)??u,u=(e.original,e.modified,void 0)...
          ╵                                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

▲ [WARNING] The "??" operator here will always return the right operand [suspicious-nullish-coalescing]

    https://esm.sh/v135/monaco-editor@0.52.0/denonext/esm/vs/language/typescript/tsMode.js:668:67421:
      668 │ ...dified,void 0)??u,u=(e.original,e.modified,void 0)??u,Pt(f=>{r(u,f),this._lastDiff=u;let g=B0.fromDif...
          ╵                                                      ~~

  The left operand of the "??" operator here will always be null or undefined, so it will never be
  returned. This usually indicates a bug in your code:

    https://esm.sh/v135/monaco-editor@0.52.0/denonext/esm/vs/language/typescript/tsMode.js:668:67392:
      668 │ ...e.original,e.modified,void 0)??u,u=(e.original,e.modified,void 0)??u,Pt(f=>{r(u,f),this._lastDiff=u;l...
          ╵                                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

▲ [WARNING] The "??" operator here will always return the right operand [suspicious-nullish-coalescing]

    https://esm.sh/v135/monaco-editor@0.52.0/denonext/esm/vs/basic-languages/javascript/javascript.js:668:66289:
      668 │ ...ginal,e.modified),u=(e.original,e.modified,void 0)??u,u=(e.original,e.modified,void 0)??u,wt(f=>{r(u,...
          ╵                                                      ~~

  The left operand of the "??" operator here will always be null or undefined, so it will never be
  returned. This usually indicates a bug in your code:

    https://esm.sh/v135/monaco-editor@0.52.0/denonext/esm/vs/basic-languages/javascript/javascript.js:668:66260:
      668 │ ...||(u=uQ(u,e.original,e.modified),u=(e.original,e.modified,void 0)??u,u=(e.original,e.modified,void 0)...
          ╵                                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

▲ [WARNING] The "??" operator here will always return the right operand [suspicious-nullish-coalescing]

    https://esm.sh/v135/monaco-editor@0.52.0/denonext/esm/vs/basic-languages/javascript/javascript.js:668:66325:
      668 │ ...dified,void 0)??u,u=(e.original,e.modified,void 0)??u,wt(f=>{r(u,f),this._lastDiff=u;let g=$b.fromDif...
          ╵                                                      ~~

  The left operand of the "??" operator here will always be null or undefined, so it will never be
  returned. This usually indicates a bug in your code:

    https://esm.sh/v135/monaco-editor@0.52.0/denonext/esm/vs/basic-languages/javascript/javascript.js:668:66296:
      668 │ ...e.original,e.modified,void 0)??u,u=(e.original,e.modified,void 0)??u,wt(f=>{r(u,f),this._lastDiff=u;l...
          ╵                                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

▲ [WARNING] The "??" operator here will always return the right operand [suspicious-nullish-coalescing]

    https://esm.sh/v135/monaco-editor@0.52.0/denonext/esm/vs/language/css/cssMode.js:668:66289:
      668 │ ...ginal,e.modified),u=(e.original,e.modified,void 0)??u,u=(e.original,e.modified,void 0)??u,yt(f=>{r(u,...
          ╵                                                      ~~

  The left operand of the "??" operator here will always be null or undefined, so it will never be
  returned. This usually indicates a bug in your code:

    https://esm.sh/v135/monaco-editor@0.52.0/denonext/esm/vs/language/css/cssMode.js:668:66260:
      668 │ ...||(u=jQ(u,e.original,e.modified),u=(e.original,e.modified,void 0)??u,u=(e.original,e.modified,void 0)...
          ╵                                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

▲ [WARNING] The "??" operator here will always return the right operand [suspicious-nullish-coalescing]

    https://esm.sh/v135/monaco-editor@0.52.0/denonext/esm/vs/language/css/cssMode.js:668:66325:
      668 │ ...dified,void 0)??u,u=(e.original,e.modified,void 0)??u,yt(f=>{r(u,f),this._lastDiff=u;let g=t1.fromDif...
          ╵                                                      ~~

  The left operand of the "??" operator here will always be null or undefined, so it will never be
  returned. This usually indicates a bug in your code:

    https://esm.sh/v135/monaco-editor@0.52.0/denonext/esm/vs/language/css/cssMode.js:668:66296:
      668 │ ...e.original,e.modified,void 0)??u,u=(e.original,e.modified,void 0)??u,yt(f=>{r(u,f),this._lastDiff=u;l...
          ╵                                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

▲ [WARNING] The "??" operator here will always return the right operand [suspicious-nullish-coalescing]

    https://esm.sh/v135/monaco-editor@0.52.0/denonext/esm/vs/basic-languages/typescript/typescript.js:668:66289:
      668 │ ...ginal,e.modified),u=(e.original,e.modified,void 0)??u,u=(e.original,e.modified,void 0)??u,wt(f=>{r(u,...
          ╵                                                      ~~

  The left operand of the "??" operator here will always be null or undefined, so it will never be
  returned. This usually indicates a bug in your code:

    https://esm.sh/v135/monaco-editor@0.52.0/denonext/esm/vs/basic-languages/typescript/typescript.js:668:66260:
      668 │ ...||(u=dQ(u,e.original,e.modified),u=(e.original,e.modified,void 0)??u,u=(e.original,e.modified,void 0)...
          ╵                                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

▲ [WARNING] The "??" operator here will always return the right operand [suspicious-nullish-coalescing]

    https://esm.sh/v135/monaco-editor@0.52.0/denonext/esm/vs/basic-languages/typescript/typescript.js:668:66325:
      668 │ ...dified,void 0)??u,u=(e.original,e.modified,void 0)??u,wt(f=>{r(u,f),this._lastDiff=u;let g=Ub.fromDif...
          ╵                                                      ~~

  The left operand of the "??" operator here will always be null or undefined, so it will never be
  returned. This usually indicates a bug in your code:

    https://esm.sh/v135/monaco-editor@0.52.0/denonext/esm/vs/basic-languages/typescript/typescript.js:668:66296:
      668 │ ...e.original,e.modified,void 0)??u,u=(e.original,e.modified,void 0)??u,wt(f=>{r(u,f),this._lastDiff=u;l...
          ╵                                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

▲ [WARNING] The "??" operator here will always return the right operand [suspicious-nullish-coalescing]

    https://esm.sh/v135/monaco-editor@0.52.0/denonext/esm/vs/language/json/jsonMode.js:668:66289:
      668 │ ...ginal,e.modified),u=(e.original,e.modified,void 0)??u,u=(e.original,e.modified,void 0)??u,yt(f=>{r(u,...
          ╵                                                      ~~

  The left operand of the "??" operator here will always be null or undefined, so it will never be
  returned. This usually indicates a bug in your code:

    https://esm.sh/v135/monaco-editor@0.52.0/denonext/esm/vs/language/json/jsonMode.js:668:66260:
      668 │ ...||(u=cJ(u,e.original,e.modified),u=(e.original,e.modified,void 0)??u,u=(e.original,e.modified,void 0)...
          ╵                                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

▲ [WARNING] The "??" operator here will always return the right operand [suspicious-nullish-coalescing]

    https://esm.sh/v135/monaco-editor@0.52.0/denonext/esm/vs/language/json/jsonMode.js:668:66325:
      668 │ ...dified,void 0)??u,u=(e.original,e.modified,void 0)??u,yt(f=>{r(u,f),this._lastDiff=u;let g=o1.fromDif...
          ╵                                                      ~~

  The left operand of the "??" operator here will always be null or undefined, so it will never be
  returned. This usually indicates a bug in your code:

    https://esm.sh/v135/monaco-editor@0.52.0/denonext/esm/vs/language/json/jsonMode.js:668:66296:
      668 │ ...e.original,e.modified,void 0)??u,u=(e.original,e.modified,void 0)??u,yt(f=>{r(u,f),this._lastDiff=u;l...
          ╵                                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

▲ [WARNING] The "??" operator here will always return the right operand [suspicious-nullish-coalescing]

    https://esm.sh/v135/monaco-editor@0.52.0/denonext/esm/vs/basic-languages/razor/razor.js:668:66289:
      668 │ ...ginal,e.modified),u=(e.original,e.modified,void 0)??u,u=(e.original,e.modified,void 0)??u,wt(f=>{r(u,...
          ╵                                                      ~~

  The left operand of the "??" operator here will always be null or undefined, so it will never be
  returned. This usually indicates a bug in your code:

    https://esm.sh/v135/monaco-editor@0.52.0/denonext/esm/vs/basic-languages/razor/razor.js:668:66260:
      668 │ ...||(u=hQ(u,e.original,e.modified),u=(e.original,e.modified,void 0)??u,u=(e.original,e.modified,void 0)...
          ╵                                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

▲ [WARNING] The "??" operator here will always return the right operand [suspicious-nullish-coalescing]

    https://esm.sh/v135/monaco-editor@0.52.0/denonext/esm/vs/basic-languages/razor/razor.js:668:66325:
      668 │ ...dified,void 0)??u,u=(e.original,e.modified,void 0)??u,wt(f=>{r(u,f),this._lastDiff=u;let g=Ub.fromDif...
          ╵                                                      ~~

  The left operand of the "??" operator here will always be null or undefined, so it will never be
  returned. This usually indicates a bug in your code:

    https://esm.sh/v135/monaco-editor@0.52.0/denonext/esm/vs/basic-languages/razor/razor.js:668:66296:
      668 │ ...e.original,e.modified,void 0)??u,u=(e.original,e.modified,void 0)??u,wt(f=>{r(u,f),this._lastDiff=u;l...
          ╵                                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

▲ [WARNING] The "??" operator here will always return the right operand [suspicious-nullish-coalescing]

    https://esm.sh/v135/monaco-editor@0.52.0/denonext/esm/vs/basic-languages/python/python.js:668:66289:
      668 │ ...ginal,e.modified),u=(e.original,e.modified,void 0)??u,u=(e.original,e.modified,void 0)??u,wt(f=>{r(u,...
          ╵                                                      ~~

  The left operand of the "??" operator here will always be null or undefined, so it will never be
  returned. This usually indicates a bug in your code:

    https://esm.sh/v135/monaco-editor@0.52.0/denonext/esm/vs/basic-languages/python/python.js:668:66260:
      668 │ ...||(u=dQ(u,e.original,e.modified),u=(e.original,e.modified,void 0)??u,u=(e.original,e.modified,void 0)...
          ╵                                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

▲ [WARNING] The "??" operator here will always return the right operand [suspicious-nullish-coalescing]

    https://esm.sh/v135/monaco-editor@0.52.0/denonext/esm/vs/basic-languages/python/python.js:668:66325:
      668 │ ...dified,void 0)??u,u=(e.original,e.modified,void 0)??u,wt(f=>{r(u,f),this._lastDiff=u;let g=Ub.fromDif...
          ╵                                                      ~~

  The left operand of the "??" operator here will always be null or undefined, so it will never be
  returned. This usually indicates a bug in your code:

    https://esm.sh/v135/monaco-editor@0.52.0/denonext/esm/vs/basic-languages/python/python.js:668:66296:
      668 │ ...e.original,e.modified,void 0)??u,u=(e.original,e.modified,void 0)??u,wt(f=>{r(u,f),this._lastDiff=u;l...
          ╵                                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

An error occurred during route handling or page rendering.
An error occurred during route handling or page rendering.
An error occurred during route handling or page rendering.
An error occurred during route handling or page rendering.
An error occurred during route handling or page rendering.
Error: The service was stopped
    at https://deno.land/x/esbuild@v0.20.2/mod.js:1059:25
    at Object.responseCallbacks.<computed> (https://deno.land/x/esbuild@v0.20.2/mod.js:679:9)
    at afterClose (https://deno.land/x/esbuild@v0.20.2/mod.js:669:28)
    at https://deno.land/x/esbuild@v0.20.2/mod.js:1972:11
    at eventLoopTick (ext:core/01_core.js:175:7)
Error: The service was stopped
    at https://deno.land/x/esbuild@v0.20.2/mod.js:1059:25
    at Object.responseCallbacks.<computed> (https://deno.land/x/esbuild@v0.20.2/mod.js:679:9)
    at afterClose (https://deno.land/x/esbuild@v0.20.2/mod.js:669:28)
    at https://deno.land/x/esbuild@v0.20.2/mod.js:1972:11
    at eventLoopTick (ext:core/01_core.js:175:7)
Error: The service was stopped
    at https://deno.land/x/esbuild@v0.20.2/mod.js:1059:25
    at Object.responseCallbacks.<computed> (https://deno.land/x/esbuild@v0.20.2/mod.js:679:9)
    at afterClose (https://deno.land/x/esbuild@v0.20.2/mod.js:669:28)
    at https://deno.land/x/esbuild@v0.20.2/mod.js:1972:11
    at eventLoopTick (ext:core/01_core.js:175:7)
Error: The service was stopped
    at https://deno.land/x/esbuild@v0.20.2/mod.js:1059:25
    at Object.responseCallbacks.<computed> (https://deno.land/x/esbuild@v0.20.2/mod.js:679:9)
    at afterClose (https://deno.land/x/esbuild@v0.20.2/mod.js:669:28)
    at https://deno.land/x/esbuild@v0.20.2/mod.js:1972:11
    at eventLoopTick (ext:core/01_core.js:175:7)
Error: The service was stopped
    at https://deno.land/x/esbuild@v0.20.2/mod.js:1059:25
    at Object.responseCallbacks.<computed> (https://deno.land/x/esbuild@v0.20.2/mod.js:679:9)
    at afterClose (https://deno.land/x/esbuild@v0.20.2/mod.js:669:28)
    at https://deno.land/x/esbuild@v0.20.2/mod.js:1972:11
    at eventLoopTick (ext:core/01_core.js:175:7)
Error: The service was stopped
    at https://deno.land/x/esbuild@v0.20.2/mod.js:1059:25
    at Object.responseCallbacks.<computed> (https://deno.land/x/esbuild@v0.20.2/mod.js:679:9)
    at afterClose (https://deno.land/x/esbuild@v0.20.2/mod.js:669:28)
    at https://deno.land/x/esbuild@v0.20.2/mod.js:1972:11
    at eventLoopTick (ext:core/01_core.js:175:7)
```

Really weird and I have to turn to NodeJS for now.

**Comment by HeavySnowJakarta** [comment]
[HeavySnowJakarta/coolcpp-online-deno-fresh](https://github.com/HeavySnowJakarta/coolcpp-online-deno-fresh) helps repro the error.

ref: #975

**Comment by marvinhagemeister** [comment]
I'm not able to reproduce the errors anymore. Maybe a newer esbuild version fixed it. I do see the warnings though.
