### ISSUE TITLE
I got this error when i defined my context inside islands directory

### ISSUE THREAD

**Issue by harshmangalam** [denoland/fresh#509]
TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'Object'
    |     property '__c' -> object with constructor 'Object'
    --- property '__v' closes the circle
    at JSON.stringify (<anonymous>)
    at render (https://deno.land/x/fresh@1.0.1/src/server/render.tsx:245:14)
    at async Object.render (https://deno.land/x/fresh@1.0.1/src/server/context.ts:404:24)
    at async https://crux.land/api/get/uYQG.ts:155:22
    at async Server.#respond (https://deno.land/std@0.128.0/http/server.ts:298:18)

**Comment by lucacasonato** [comment]
You can not pass anything but plain JS objects and primitives to islands. See https://fresh.deno.dev/docs/concepts/islands.

**Comment by harshmangalam** [comment]
Okay thanks but how can i implement global context that accept children.
