### ISSUE TITLE
Using headless-ui with Fresh

### ISSUE THREAD

**Issue by ClaudiuCeia** [denoland/fresh#585]
Hi,

I'm trying to use the Headless UI [`Tabs` component](https://headlessui.com/react/tabs) in a Fresh project, but I'm running into issues. Headless UI seemed like a natural go-to since Fresh ships with tailwind (via twind). It doesn't work out of the box since it's made for React, so I get:

```
This JSX tag's 'children' prop expects a single child of type 'ReactNode | ((bag: TabsRenderPropArg) => ReactElement<any, string | JSXElementConstructor<any>>)', but multiple children were provided.deno-ts(2746)
``` 

Since this is a React library, I tried using the Preact compat layer, like so:

```ts
import { Tabs } from "https://esm.sh/@headlessui/react@1.6.6?alias=react:preact/compat";
```

This got rid of the Typescript errors I had, but I get runtime errors:

```
TypeError: Cannot read properties of undefined (reading '__H')
    at f (https://esm.sh/v87/preact@10.10.0/X-YS9yZWFjdDpwcmVhY3QvY29tcGF0/deno/hooks.js:2:217)
    at A (https://esm.sh/v87/preact@10.10.0/X-YS9yZWFjdDpwcmVhY3QvY29tcGF0/deno/hooks.js:2:935)
    at R (https://esm.sh/v87/preact@10.10.0/X-YS9yZWFjdDpwcmVhY3QvY29tcGF0/deno/hooks.js:2:695)
    at C (https://esm.sh/v87/@headlessui/react@1.6.6/X-YS9yZWFjdDpwcmVhY3QvY29tcGF0/deno/react.js:2:6377)
    at https://esm.sh/v87/@headlessui/react@1.6.6/X-YS9yZWFjdDpwcmVhY3QvY29tcGF0/deno/react.js:5:66648
    at Object.t (https://esm.sh/v87/preact@10.10.0/X-YS9yZWFjdDpwcmVhY3QvY29tcGF0/deno/compat.js:2:1609)
    at h (https://esm.sh/v86/preact-render-to-string@5.2.0/X-ZC9wcmVhY3RAMTAuOC4y/deno/preact-render-to-string.js:4:1003)
    at h (https://esm.sh/v86/preact-render-to-string@5.2.0/X-ZC9wcmVhY3RAMTAuOC4y/deno/preact-render-to-string.js:9:66)
    at h (https://esm.sh/v86/preact-render-to-string@5.2.0/X-ZC9wcmVhY3RAMTAuOC4y/deno/preact-render-to-string.js:9:66)
    at h (https://esm.sh/v86/preact-render-to-string@5.2.0/X-ZC9wcmVhY3RAMTAuOC4y/deno/preact-render-to-string.js:9:66)
```

Then I check the Preact documentation again and [added all of the rest of the aliases](https://preactjs.com/guide/v10/getting-started#aliasing-react-to-preact):

```ts
import { Tab } from "https://esm.sh/@headlessui/react@1.6.6?alias=react:preact/compat,react-dom/test-utils:preact/test-utils,react-dom:preact-compat,react/jsx-runtime:preact/jsx-runtime";
```

But that brings back the Typescript errors as well as the runtime error (slightly different paths due to different aliases). 

So I'm at a loss here - can I even get this to work?

**Comment by lucacasonato** [comment]
Importing `https://esm.sh/@headlessui/react@1.6.6?alias=react:preact/compat,react-dom:preact/compat,@types/react:preact/compat&deps=preact@10.10.0` works for me.

Ideally `https://esm.sh/@headlessui/react@1.6.6?alias=react:preact/compat,react-dom:preact/compat,@types/react:preact/compat&external=preact` would work, but that seems to be running into some esm.sh bug. cc @ije: the `external=preact` is not applying to most imports it seems.
