### ISSUE TITLE
Static 

### ISSUE THREAD

**Issue by MarkBennett** [denoland/fresh#648]
**Describe the bug**
I'm seeing a 500 error when accessing the concepts page on static files.

https://fresh.deno.dev/docs/concepts/static-files

![Screen Shot 2022-08-23 at 12 58 32 PM](https://user-images.githubusercontent.com/61872/186241349-6051a987-d690-4d76-8bf9-1f2266a77637.png)

I forked the latest `main` branch and deployed to my own Deno Deploy instance at:

https://mark-bennett-fresh.deno.dev/docs/concepts/static-files

Where I see this error in the logs:

```
An error occurred during route handling or page rendering. TypeError: Failed to extract front matter
    at extract (https://deno.land/std@0.150.0/encoding/front_matter.ts:34:11)
    at GET (file:///src/www/routes/docs/[...slug].tsx:25:35)
    at async https://crux.land/api/get/uYQG.ts:83:36
    at async Server.#respond (https://deno.land/std@0.150.0/http/server.ts:219:24)
```

![Screen Shot 2022-08-23 at 12 56 49 PM](https://user-images.githubusercontent.com/61872/186241548-e9c1c0bf-f182-4145-89b2-b141a23deedc.png)

**Comment by MarkBennett** [comment]
I should note that I don't see this when I run `deno task www` locally.
