### ISSUE TITLE
Docker build fails with 'reason' does not exist on type 'AbortSignal'

### ISSUE THREAD

**Issue by dweidenfeld** [denoland/fresh#660]
Hey, 

probably this is a know issue already, but I was not able to solve it myself.

When I create a fresh project on 1.24.3 with the command

```sh
deno run -A -r https://fresh.deno.dev my-project
```

and then try to let it build using Docker with 

```Dockerfile
FROM denoland/deno:1.24.3
WORKDIR /app
COPY . /app
RUN deno bundle --import-map=import_map.json main.ts > app.ts
```

it fails with the following error:

```sh
#10 35.09 error: TS2339 [ERROR]: Property 'reason' does not exist on type 'AbortSignal'.
#10 35.09     return Promise.reject(createAbortError(signal.reason));
#10 35.09                                                   ~~~~~~
#10 35.09     at https://deno.land/std@0.150.0/async/abortable.ts:27:51
#10 35.09 
#10 35.09 TS2339 [ERROR]: Property 'reason' does not exist on type 'AbortSignal'.
#10 35.09   const abort = () => waiter.reject(createAbortError(signal.reason));
#10 35.09                                                             ~~~~~~
#10 35.09     at https://deno.land/std@0.150.0/async/abortable.ts:30:61
#10 35.09 
#10 35.09 TS2339 [ERROR]: Property 'reason' does not exist on type 'AbortSignal'.
#10 35.09     throw createAbortError(signal.reason);
#10 35.09                                   ~~~~~~
#10 35.09     at https://deno.land/std@0.150.0/async/abortable.ts:46:35
#10 35.09 
#10 35.09 TS2339 [ERROR]: Property 'reason' does not exist on type 'AbortSignal'.
#10 35.09   const abort = () => waiter.reject(createAbortError(signal.reason));
#10 35.09                                                             ~~~~~~
#10 35.09     at https://deno.land/std@0.150.0/async/abortable.ts:49:61
#10 35.09 
#10 35.09 TS2304 [ERROR]: Cannot find name 'URLPattern'.
#10 35.09   const internalRoutes: Record<string, { pattern: URLPattern, methods: Record<string, MatchHandler<T>> }> = {};
#10 35.09                                                   ~~~~~~~~~~
#10 35.09     at https://crux.land/api/get/uYQG.ts:132:51
#10 35.09 
#10 35.09 TS2304 [ERROR]: Cannot find name 'URLPattern'.
#10 35.09       pattern: new URLPattern({ pathname: path }),
#10 35.09                    ~~~~~~~~~~
#10 35.09     at https://crux.land/api/get/uYQG.ts:141:20
#10 35.09 
#10 35.09 TS2304 [ERROR]: Cannot find name 'URLPattern'.
#10 35.09   compiledPattern: URLPattern;
#10 35.09                    ~~~~~~~~~~
#10 35.09     at https://deno.land/x/fresh@1.0.2/src/server/types.ts:202:20
#10 35.09 
#10 35.09 TS2339 [ERROR]: Property 'readable' does not exist on type 'File'.
#10 35.09         return new Response(file.readable, { headers });
#10 35.09                                  ~~~~~~~~
#10 35.09     at https://deno.land/x/fresh@1.0.2/src/server/context.ts:546:34
#10 35.09 
#10 35.09 TS2304 [ERROR]: Cannot find name 'URLPattern'.
#10 35.09   const compiledPattern = new URLPattern({ pathname: pattern });
#10 35.09                               ~~~~~~~~~~
#10 35.09     at https://deno.land/x/fresh@1.0.2/src/server/context.ts:722:31
#10 35.09 
#10 35.09 Found 9 errors.
------
executor failed running [/bin/sh -c deno bundle --import-map=import_map.json main.ts > app.ts]: exit code: 1
```

any ideas?

thanks & cheers
Dominik

**Comment by dweidenfeld** [comment]
Okay, I don't know, but it was solved automatically with 1.25.0 for me
