### ISSUE TITLE
Uncaught PermissionDenied when trying to create a New Fresh App

### ISSUE THREAD

**Issue by og-dev** [denoland/fresh#669]
```
I:\denoapp>deno run -A -r https://fresh.deno.dev newfreshapp
Download https://fresh.deno.dev/
Download https://deno.land/x/fresh@1.0.2/init.ts
Download https://deno.land/x/fresh@1.0.2/src/dev/deps.ts
Download https://deno.land/x/fresh@1.0.2/src/dev/error.ts
Download https://deno.land/x/fresh@1.0.2/src/dev/mod.ts
Download https://deno.land/std@0.150.0/flags/mod.ts
Download https://deno.land/std@0.150.0/fs/walk.ts
Download https://deno.land/std@0.150.0/path/mod.ts
Download https://deno.land/std@0.150.0/semver/mod.ts
Download https://deno.land/std@0.150.0/_util/assert.ts
Download https://deno.land/std@0.150.0/fs/_util.ts
Download https://deno.land/std@0.150.0/_util/os.ts
Download https://deno.land/std@0.150.0/path/_interface.ts
Download https://deno.land/std@0.150.0/path/common.ts
Download https://deno.land/std@0.150.0/path/glob.ts
Download https://deno.land/std@0.150.0/path/posix.ts
Download https://deno.land/std@0.150.0/path/separator.ts
Download https://deno.land/std@0.150.0/path/win32.ts
Download https://deno.land/std@0.150.0/path/_constants.ts
Download https://deno.land/std@0.150.0/path/_util.ts
Do you want to use 'twind' (https://twind.dev/) for styling? [y/N] error: Uncaught PermissionDenied: Access is denied. (os error 5)
  ? confirm(USE_TWIND_MESSAGE)
    ^
    at readSync (deno:runtime/js/12_io.js:95:23)
    at Stdin.readSync (deno:runtime/js/40_files.js:171:14)
    at readLineFromStdinSync (deno:runtime/js/41_prompt.js:55:23)
    at confirm (deno:runtime/js/41_prompt.js:29:20)
    at https://deno.land/x/fresh@1.0.2/init.ts:79:5

I:\denoapp>
```

New app can't be created due this error. 
There are no permissions problems in that folder. I can create files and folders manually.

OS: Windows 7
Deno 1.25.0

Any idea?

**Comment by lucacasonato** [comment]
Deno does not support on Windows 7. Please update to a newer Windows version.
