### ISSUE TITLE
twind css function causes page to throw error

### ISSUE THREAD

**Issue by jhechtf** [denoland/fresh#746]
I was attempting to use the following code in a `_404` page and ended up getting an error

## Code

```tsx
import { UnknownPageProps } from '$fresh/server.ts';
import { css, tw } from 'twind/css';

const captionCss = css({
  '&::before': {
    content: '-',
  }
});

export default function Base404({ }: UnknownPageProps) {

  return (
    <div className="mx-auto max-w-screen-xl pt-10">
      <h1 className="text-4xl font-semibold text-gray-700">
        Page Not Found
      </h1>

      <figure>
        <blockquote className="border-l-4 border-green-400 pl-5 my-2 ">
          To find nothing in the infinite is equal parts impressive and alarming.
        </blockquote>

        <figcaption className={tw(captionCss)}>
          That One Guy
        </figcaption>

      </figure>

    </div>
  )
}
```

## Error

```
An error occured during route handling or page rendering.

ReferenceError: document is not defined
    at mt (https://esm.sh/v94/twind@0.16.17/deno/twind.js:3:16536)
    at wt (https://esm.sh/v94/twind@0.16.17/deno/twind.js:3:16687)
    at Bt (https://esm.sh/v94/twind@0.16.17/deno/twind.js:3:30247)
    at r (https://esm.sh/v94/twind@0.16.17/deno/twind.js:3:31251)
    at t (https://esm.sh/v94/twind@0.16.17/deno/twind.js:3:31215)
    at Vt.tw.Object.defineProperties.theme.get.o (https://esm.sh/v94/twind@0.16.17/deno/twind.js:3:31315)
    at Object.Base404 (file:///C:/Users/Jim/deno-fresh-project/routes/_404.tsx:23:32)
    at https://esm.sh/v94/preact-render-to-string@5.2.3/X-ZS8q/deno/preact-render-to-string.js:12:1590
    at T (https://esm.sh/v94/preact-render-to-string@5.2.3/X-ZS8q/deno/preact-render-to-string.js:12:1617)
    at T (https://esm.sh/v94/preact-render-to-string@5.2.3/X-ZS8q/deno/preact-render-to-string.js:12:1693)
```

I looked to see if there was a way to import the `css` function from the base `twind` directory (as I don't use twind normally), but I don't see that exported so I'm not sure what the going forward way would be here.

**Comment by lucacasonato** [comment]
What version of Fresh are you using?

**Comment by jhechtf** [comment]
Latest version as of writing this -- literally spun the project up about an hour or so before I reported this bug.

**Comment by lucacasonato** [comment]
@jhechtf Would you be so kind to send over your `main.ts`, `twind.config.ts`, and `import_map.json`? Best would be a repo that I can just check out.

**Comment by jhechtf** [comment]
It was a bare bones repo, nothing had been touched but this recreates it for me.

https://github.com/jhechtf/deno-fresh-twind-css-err

**Comment by lucacasonato** [comment]
Oh, I think I know the root cause. Let me try fix it.

**Comment by lucacasonato** [comment]
~~Workaround: call `css()` function inside of your component rather than in global scope.~~ This is not the issue.

**Comment by lucacasonato** [comment]
Can you try run `deno cache --reload main.ts`?

**Comment by jhechtf** [comment]
seems to have fixed it I think - what do you think was the issue?
