### ISSUE TITLE
After compiling fresh does not run: ReferenceError: React is not defined after compilation

### ISSUE THREAD

**Issue by og-dev** [denoland/fresh#785]
Create a new app

deno run -A -r https://fresh.deno.dev newapp

then

`deno compile --import-map=import_map.json -o newapp -A main.ts`

Result (_when you try to load the page_)

```
An error occured during route handling or page rendering.

ReferenceError: React is not defined
    at Object.Home (/denoapp/compapp/routes/index.tsx:3:5)
    at https://esm.sh/v95/preact-render-to-string@5.2.4/X-ZS8q/deno/preact-render-to-string.js:12:1626
    at E (https://esm.sh/v95/preact-render-to-string@5.2.4/X-ZS8q/deno/preact-render-to-string.js:12:1653)
    at E (https://esm.sh/v95/preact-render-to-string@5.2.4/X-ZS8q/deno/preact-render-to-string.js:12:1729)
    at E (https://esm.sh/v95/preact-render-to-string@5.2.4/X-ZS8q/deno/preact-render-to-string.js:12:1729)
    at E (https://esm.sh/v95/preact-render-to-string@5.2.4/X-ZS8q/deno/preact-render-to-string.js:12:1729)
    at E (https://esm.sh/v95/preact-render-to-string@5.2.4/X-ZS8q/deno/preact-render-to-string.js:12:1729)
    at q (https://esm.sh/v95/preact-render-to-string@5.2.4/X-ZS8q/deno/preact-render-to-string.js:12:316)
    at realRender (https://deno.land/x/fresh@1.1.1/src/server/render.ts:109:20)
    at Object.render (https://deno.land/x/fresh@1.1.1/src/server/render.ts:128:13)
```

**Comment by lucacasonato** [comment]
This specific error seems like a Deno bug. Once that is fixed Fresh will still not work in `deno compile` however, because Fresh relies on the presence of the original island source files on disk (which is not the case with `deno compile`).

**Comment by og-dev** [comment]
> 

Does this mean that a Fresh application cannot be compiled now, nor in the future?

**Comment by lucacasonato** [comment]
Yes, you can not currently use `deno compile` with fresh applications.

**Comment by og-dev** [comment]
Thanks!!

**Comment by NanoSpicer** [comment]
It should work. Wouldn't it be enough to pack the assets alongside the fat binary whenever "compiling"?  🤷🏻

**Comment by barcellos-pedro** [comment]
I hope it works soon, or maybe we could have a workaround

**Comment by ghost** [comment]
I did find a way for it to work but the js doesn't seem to load after the page loads.
You just need to import React in each page/component,
```
import * as React from "preact/compat";
```
And add this to the compilerOptions in deno.json,
```
 "compilerOptions": {
    "jsx": "react-jsx",
    "jsxImportSource": "https://esm.sh/preact@10.15.1"
  }
 ```

**Comment by ghost** [comment]
> I did find a way for it to work but the js doesn't seem to load after the page loads. You just need to import React in each page/component,
> 
> ```
> import * as React from "preact/compat";
> ```
> 
> And add this to the compilerOptions in deno.json,
> 
> ```
>  "compilerOptions": {
>     "jsx": "react-jsx",
>     "jsxImportSource": "https://esm.sh/preact@10.15.1"
>   }
> ```


@pyrossh  Thank You very much.

**Comment by wderezin** [comment]
@pyrossh  solution also worked when trying to run fresh as a sub workspace.
