### ISSUE TITLE
File upload using multipart/form-data

### ISSUE THREAD

**Issue by itsahsiao** [denoland/fresh#819]
Hi, I have a form with a file upload and need some help figuring out how to get it working with deno fresh. I'd like to get the file that was uploaded and submitted via the form and just save it on disk.

My route looks something like this:
```
import { Handlers } from "$fresh/server.ts";
// import { MultipartReader } from "https://deno.land/std@0.89.0/mime/mod.ts";
import { MultipartReader } from "https://deno.land/x/denjucks@1.1.1/src/deps/path/std/mime/mod.ts";

export const: handler: Handlers {
  GET(_req, ctx) {
    return ctx.render();
  },
  async POST(req, ctx) {
    const ct = req.headers.get("content-type");
    let boundary = "";
    if (ct?.startsWith("multipart/form-data")) {
      boundary = ct?.split(";")[1]?.split("=")[1];
    }
    const reader = req.body?.getReader();
    if (reader) {
      const mr = new MultipartReader(reader, boundary);
      const form = await mr.readForm();
      console.log(form);
    }
    // some more logic
  }
}

export default function Form() {
  return (
    <form
      method="POST"
      encType="multipart/form-data"
     >
      <label class="text-gray-500 text-xs mb-2" for="image">
        Upload image
      </label>
      <input
        accept="image/jpeg,image/gif,image/png,application/pdf,image/x-eps"
        name="image"
        type="file"
        class="text-xs mb-6"
      />
    </form>
  );
}
```

It always fails either at the `MultipartReader` or at `mr.readForm()`.
I have tried passing `req.body` or `req.body.getReader()` as the first argument to MultipartReader.
I've also tried different imports for the MultipartReader, as some seem to be outdated / deprecated now.

I get errors such as:
```
An error occurred during route handling or page rendering. AssertionError: negative read
    at assert (https://deno.land/x/denjucks@1.1.1/src/deps/path/std/testing/asserts.ts:135:11)
    at BufReader._fill (https://deno.land/x/denjucks@1.1.1/src/deps/path/std/io/bufio.ts:90:7)
    at async BufReader.readSlice (https://deno.land/x/denjucks@1.1.1/src/deps/path/std/io/bufio.ts:348:9)
    at async MultipartReader.nextPart (https://deno.land/x/denjucks@1.1.1/src/deps/path/std/mime/multipart.ts:364:20)
    at async MultipartReader.readForm (https://deno.land/x/denjucks@1.1.1/src/deps/path/std/mime/multipart.ts:290:17)
    at async POST (file:///Users/user/user/app/routes/form.tsx:61:18)
    at async https://deno.land/x/rutt@0.0.13/mod.ts:228:22
    at async Server.#respond (https://deno.land/std@0.150.0/http/server.ts:298:18)
```

```
An error occurred during route handling or page rendering. TypeError: this.rd.read is not a function
    at BufReader._fill (https://deno.land/x/denjucks@1.1.1/src/deps/path/std/io/bufio.ts:85:32)
    at BufReader.readSlice (https://deno.land/x/denjucks@1.1.1/src/deps/path/std/io/bufio.ts:348:20)
    at MultipartReader.nextPart (https://deno.land/x/denjucks@1.1.1/src/deps/path/std/mime/multipart.ts:364:41)
    at MultipartReader.readForm (https://deno.land/x/denjucks@1.1.1/src/deps/path/std/mime/multipart.ts:290:28)
    at POST (file:///Users/user/user/app/routes/form.tsx:61:27)
    at routes.<computed> (https://deno.land/x/fresh@1.1.1/src/server/context.ts:515:13)
    at https://deno.land/x/rutt@0.0.13/mod.ts:228:28
    at https://deno.land/x/fresh@1.1.1/src/server/context.ts:364:27
    at Object.next (https://deno.land/x/fresh@1.1.1/src/server/context.ts:347:34)
    at handler (file:///Users/user/user/app/routes/_middleware.ts:27:14)
```

```
An error occurred during route handling or page rendering. TypeError: ReadableStream is locked.
    at setUpReadableStreamDefaultReader (deno:ext/web/06_streams.js:3097:13)
    at new ReadableStreamDefaultReader (deno:ext/web/06_streams.js:4618:7)
    at acquireReadableStreamDefaultReader (deno:ext/web/06_streams.js:300:12)
    at ReadableStream.getReader (deno:ext/web/06_streams.js:4466:16)
    at POST (file:///Users/user/user/app/routes/form.tsx:54:30)
    at routes.<computed> (https://deno.land/x/fresh@1.1.1/src/server/context.ts:515:13)
    at https://deno.land/x/rutt@0.0.13/mod.ts:228:28
    at https://deno.land/x/fresh@1.1.1/src/server/context.ts:364:27
    at Object.next (https://deno.land/x/fresh@1.1.1/src/server/context.ts:347:34)
    at handler (file:///Users/user/user/app/app/routes/_middleware.ts:27:14)
```

References I used:
https://medium.com/deno-the-complete-reference/handling-multipart-form-data-in-deno-66ca008c5c56
https://medium.com/deno-the-complete-reference/handling-file-uploads-via-multipart-form-data-in-deno-b4c860647cc3
https://dev.to/hyper/uploading-files-with-deno-2epi

Any help would be much appreciated!

**Comment by itsahsiao** [comment]
I managed to solve it. The MultipartReader is not needed at all 😮‍💨  

Using `await req.formData()` is sufficient, then reading and writing the file.

Here's what my handler ended up looking like, for anyone interested:
```
  async POST(req, ctx) {
    const formData = await req.formData();
    const file = formData.get("file") as File | null;

    if (file) {
      try {
        const reader = file.stream().getReader();
        const result = await reader.read();
        if (result.value) {
          await Deno.writeFile(
            "tmp/${file.name}",
            result.value,
          );
        }
      } catch (e) {
        console.error(e);
      }
    }
    
    // some more logic
  }
```

**Comment by saminiemi** [comment]
Hi @itsahsiao !

We also fought hours with upload, and finally solved the problem you describe with readerFromStreamReader like this:

```
import { readerFromStreamReader } from "https://deno.land/std@0.92.0/io/mod.ts";
...

const mr = new MultipartReader(readerFromStreamReader(reader)), boundary);
```

But your solution using req.formData() is much more elegant, so we of course will use it. 

Thanks! :)

**Comment by kt3k** [comment]
BTW the above example only supports the case when the file has only single chunk (i.e. file is small).

We need to iterate on `reader` or use `pipeTo` method to process the entire file.

```ts
const { writable } = await Deno.open(`tmp/${file.name}`, { write: true, create: true }); 
file.stream().pipeTo(writable);
```
