### ISSUE TITLE
cli_test ci failure on canary + windows latest

### ISSUE THREAD

**Issue by hashrock** [denoland/fresh#884]
https://github.com/denoland/fresh/actions/runs/3400285581/jobs/5655674573

```
/with-island hydration ... ok (2s)
error: Test failed

 ERRORS 

fresh-init => ./tests/cli_test.ts:37:6
error: Error: The process cannot access the file because it is being used by another process. (os error 32), remove 'C:\Users\RUNNER~1\AppData\Local\Temp\e5994c14'
    await Deno.remove(tmpDirName, { recursive: true });
    ^
    at async Object.remove (deno:runtime/js/30_fs.js:167:5)
    at async fn (file:///D:/a/fresh/fresh/tests/cli_test.ts:172:5)

 FAILURES 

fresh-init => ./tests/cli_test.ts:37:6

FAILED | 44 passed (16 steps) | 1 failed | 1 ignored (37s)

Error: Process completed with exit code 1.
```

It doesn't reproduce my Windows 11 + deno canary

**Comment by kt3k** [comment]
maybe we should revert https://github.com/denoland/fresh/pull/280 ?

**Comment by hashrock** [comment]
I don't know why, but this no longer occurs. I will close it for now.
