### ISSUE TITLE
error: Expected ], got as at https://deno.land/std@0.150.0/flags/mod.ts:72:20

### ISSUE THREAD

**Issue by k-koehler** [denoland/fresh#885]
Trying to install fresh for the first time. I'm following the docs which ask me to run `deno run -A -r https://fresh.deno.dev my-project`. I get an error. Here is the output of the command:

```zsh
➜  myfolder deno run -A -r https://fresh.deno.dev my-project
Download https://fresh.deno.dev/
Download https://deno.land/x/fresh@1.1.2/init.ts
Download https://deno.land/x/fresh@1.1.2/src/dev/deps.ts
Download https://deno.land/x/fresh@1.1.2/src/dev/error.ts
Download https://deno.land/x/fresh@1.1.2/src/dev/mod.ts
Download https://deno.land/x/fresh@1.1.2/src/dev/imports.ts
Download https://deno.land/std@0.150.0/path/mod.ts
Download https://deno.land/std@0.150.0/fs/walk.ts
Download https://deno.land/std@0.150.0/flags/mod.ts
Download https://deno.land/std@0.150.0/semver/mod.ts
Download https://deno.land/x/ts_morph@16.0.0/mod.ts
Download https://deno.land/std@0.150.0/_util/assert.ts
Download https://deno.land/std@0.150.0/fs/_util.ts
Download https://deno.land/std@0.150.0/_util/os.ts
Download https://deno.land/std@0.150.0/path/win32.ts
Download https://deno.land/std@0.150.0/path/posix.ts
Download https://deno.land/std@0.150.0/path/common.ts
Download https://deno.land/std@0.150.0/path/separator.ts
Download https://deno.land/std@0.150.0/path/_interface.ts
Download https://deno.land/std@0.150.0/path/glob.ts
error: Expected ], got as at https://deno.land/std@0.150.0/flags/mod.ts:72:20
```

Some relevant info:

```zsh
➜  myfolder deno --version
deno 1.4.2
v8 8.7.75
typescript 4.0.3
➜  myfolder uname -a
Linux MSI 4.19.104-microsoft-standard #1 SMP Wed Feb 19 06:37:35 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

Running on ubuntu wsl2

Thanks!

**Comment by garyhe0780** [comment]
I think it's your `Deno` version issue, you should have `Deno 1.25.0` or later installed.

**Comment by lino-levan** [comment]
Deno `1.4.2` was released in september of 2020 (it's been two years). I think updating it would fix this issue.

**Comment by codesculpture** [comment]
This issue was solved i guess so it can be closed😄 @hashrock
