### ISSUE TITLE
Using the dev build of preact errors

### ISSUE THREAD

**Issue by raoulmillais** [denoland/fresh#887]
If I change the import map url for preact to include `?dev&sourcemap` the boilerplate fresh app bombs with 
```
Error: <Head> component is not supported in the browser, or during suspense renders.
    at Object.Head (https://deno.land/x/fresh@1.1.2/src/runtime/head.ts:15:11)
    at https://esm.sh/v96/preact-render-to-string@5.2.4/X-ZS8q/deno/preact-render-to-string.js:12:1626
    at E (https://esm.sh/v96/preact-render-to-string@5.2.4/X-ZS8q/deno/preact-render-to-string.js:12:1653)
    at E (https://esm.sh/v96/preact-render-to-string@5.2.4/X-ZS8q/deno/preact-render-to-string.js:12:918)
    at E (https://esm.sh/v96/preact-render-to-string@5.2.4/X-ZS8q/deno/preact-render-to-string.js:12:1729)
    at E (https://esm.sh/v96/preact-render-to-string@5.2.4/X-ZS8q/deno/preact-render-to-string.js:12:1729)
    at E (https://esm.sh/v96/preact-render-to-string@5.2.4/X-ZS8q/deno/preact-render-to-string.js:12:1729)
    at E (https://esm.sh/v96/preact-render-to-string@5.2.4/X-ZS8q/deno/preact-render-to-string.js:12:1729)
    at E (https://esm.sh/v96/preact-render-to-string@5.2.4/X-ZS8q/deno/preact-render-to-string.js:12:1729)
    at E (https://esm.sh/v96/preact-render-to-string@5.2.4/X-ZS8q/deno/preact-render-to-string.js:12:1729)
```

Note that this is when rendering the `index` route on the server.  The underlying cause is an undefined `Context` for `ComponentChildren[]`

```
Caused by TypeError: Cannot read properties of undefined (reading 'context')
    at M (https://esm.sh/stable/preact@10.11.0/deno/hooks.js:2:1451)
    at Object.Head (https://deno.land/x/fresh@1.1.2/src/runtime/head.ts:13:15)
    at https://esm.sh/v96/preact-render-to-string@5.2.4/X-ZS8q/deno/preact-render-to-string.js:12:1626
    at E (https://esm.sh/v96/preact-render-to-string@5.2.4/X-ZS8q/deno/preact-render-to-string.js:12:1653)
    at E (https://esm.sh/v96/preact-render-to-string@5.2.4/X-ZS8q/deno/preact-render-to-string.js:12:918)
    at E (https://esm.sh/v96/preact-render-to-string@5.2.4/X-ZS8q/deno/preact-render-to-string.js:12:1729)
    at E (https://esm.sh/v96/preact-render-to-string@5.2.4/X-ZS8q/deno/preact-render-to-string.js:12:1729)
    at E (https://esm.sh/v96/preact-render-to-string@5.2.4/X-ZS8q/deno/preact-render-to-string.js:12:1729)
    at E (https://esm.sh/v96/preact-render-to-string@5.2.4/X-ZS8q/deno/preact-render-to-string.js:12:1729)
    at E (https://esm.sh/v96/preact-render-to-string@5.2.4/X-ZS8q/deno/preact-render-to-string.js:12:1729)
```

Not being able to use the dev build (sourcemaps) of preact in the browser is important for me because it seems to be the only way  to get reasonable debugging messages out of preact.

**Comment by raoulmillais** [comment]
Here's a bit more context about what I need to solve.  When `revive`ing an island I get the following cryptic error message:

```
15:17:13.889 Uncaught TypeError: _.__ is not a function
    Preact 26
    walk main.ts:45
    walk main.ts:61
    walk main.ts:61
    walk main.ts:61
    walk main.ts:61
    walk main.ts:61
    walk main.ts:61
    walk main.ts:61
    walk main.ts:61
    walk main.ts:61
    walk main.ts:61
    walk main.ts:61
    walk main.ts:61
    walk main.ts:61
    walk main.ts:61
    walk main.ts:61
    walk main.ts:61
    walk main.ts:61
    walk main.ts:62
    walk main.ts:62
    walk main.ts:62
    revive main.ts:64
    <anonymous> (index):154
hooks.js:2:3331
```
<details>
<summary>Inside the "Preact (26)" node</summary>

```
        p
        R
        setTimeout handler*u290
        S
        diffed
        diffed
        W
        G
        ne
        W
        G
        ne
        W
        G
        W
        G
        W
        G
        W
        G
        W
        G
        W
        G
        W
        re
```

</details>

The most recent line in the trace for `main.ts` (45) in fresh is:
```typescript
       h(islands[id], props[Number(n)]),
```
and line 61 is
```typescript
    if (sib) walk(sib);
```

What I can deduce so far is that `h` in preact is using `preact/hooks` internally and whichever call it is making in hooks is failing.  As you can see in the "Preact (26)" node I lose all useful debugging information.  I don't think I can diagnose any further without having the preact code sourcemapped in the client, but I'm open to suggestions if I've missed something!

**Comment by raoulmillais** [comment]
I got to the bottom of the problem.  It was the way I was  `import_map`ing the dev build. Because you have to put a querystring onto the esm.sh url you cannot use the "package" import speifiers - I removed them and added explicit import maps for the `preact/hooks` and `preact/jsx-runtime` with the appropriate querystring and it worked.

**Comment by jimmernauts** [comment]
@raoulmillais did you end up solving the underlying problem? I have the same issue, walk main.ts:45 is the line it dies on.
