### ISSUE TITLE
Styled components (Deno is not defined at _arch)

### ISSUE THREAD

**Issue by NicoZweifel** [denoland/fresh#927]
I was messing around with different component libraries and CSS Frameworks in deno/fresh and tried to add styled components to a new project.

I used the plugin system (although my impl is very limited and more context options would probably improve this significantly).
```ts
export default function styledComponents(): Plugin {
 return {
    name: "styled-components",
    render: (ctx) => {
      ctx.render()
      const sheet = new ServerStyleSheet();
      try {
      renderToString(
       sheet.collectStyles(
       <>
        <Home/>
        <Greet 
            url={new URL("localhost.com:8000")}
            route="test"
            params={{}} 
            data={"test"}/>  
        </>)
      );
      const styleTags = sheet.getStyleTags();
      const doc = new DOMParser().parseFromString(styleTags, "text/html");
      if(doc == null) return {
        styles: []
      }
      const matches : string [] = [...doc.querySelectorAll('style')]
        .map(style => style.textContent)
        .filter(x => x != null && x.length > 0)
        .map( x=> x as string);
      return {
        styles: matches.map(x => {
          return {
            cssText: x,
            id: '___STYLED'
          }
        })
      }
      } catch (error) {
        console.error(error);
      } finally {
        sheet.seal();
      }
      return {
        styles: []
      }
    }
 }
}
```
The SSR seems okay:
![image](https://user-images.githubusercontent.com/34443492/204844051-252a3fb9-880b-43b7-b19f-59faf929d5e0.png)
![image](https://user-images.githubusercontent.com/34443492/204844230-f5c62fa8-ac5d-462f-a417-ad7f42bc8032.png)

But the hydrate function is missing still and not sure how to implement it yet.
I have uploaded a demo project at: https://github.com/NicoZweifel/fresh-styled-components

**Comment by NicoZweifel** [comment]
After some more research I am still encountering this error on the client side:

`Uncaught ReferenceError: Deno is not defined
    at _arch (process.ts:13:3)
    at process.ts:23:21
_arch @ process.ts:13
(anonymous) @ process.ts:23`

Could this be related to a broken Plugin or is this a bug somewhere else?
The Hydrate/main.ts function is never called.

**Comment by UrielCh** [comment]
I have the same issue today ...

it looks to occur if use:
import { render } from "https://deno.land/x/gfm@0.1.26/mod.ts";
in an island.

....

should that work ?
is gfm is too large and should only by used in SSR ?

**Comment by NicoZweifel** [comment]
Yea it seems like that it is caused by code  that is supposed to be server only exposed to the client.
I'll probably dig some more in the coming days when I find some time.

**Comment by marvinhagemeister** [comment]
The `styled-component` library as is, is something we're likely never going to support. The way it works is that every component _has_ to run a tiny amount of JavaScript to match the correct styles. Every component needs to become an island essentially. This kinda defeats the purpose of going with Fresh in the first place. We strongly encourage to go with any other styling option.
