### ISSUE TITLE
Error: Key length is zero

### ISSUE THREAD

**Issue by vwkd** [denoland/fresh#965]
Sometimes running `deno task start` throws the following error

```sh
Task start deno run -A --watch=static/,routes/ src/dev.ts
Watcher Process started.
The manifest has been generated for X routes and Y islands.
error: Uncaught (in promise) Error: Key length is zero
  await import(entrypoint);
  ^
    at async dev (https://deno.land/x/fresh@1.1.0/src/dev/mod.ts:187:3)
    at async file:///[path-to-repo]/src/dev.ts:5:1
Watcher Process finished. Restarting on file change...
```

While deploying to Deno Deploy continues to work without problems.

**Comment by vwkd** [comment]
Ok, running `deno run src/main.ts` gave the actual error

```sh
error: Uncaught DataError: Key length is zero
    return crypto.subtle.importKey(
                         ^
    at importKeyHMAC (deno:ext/crypto/00_crypto.js:2937:13)
    at SubtleCrypto.importKey (deno:ext/crypto/00_crypto.js:929:18)
    at getCryptoKey (https://deno.land/x/jose@v4.11.2/runtime/get_sign_verify_key.ts:16:26)
    at sign (https://deno.land/x/jose@v4.11.2/runtime/sign.ts:8:27)
    at FlattenedSign.sign (https://deno.land/x/jose@v4.11.2/jws/flattened/sign.ts:131:29)
    at CompactSign.sign (https://deno.land/x/jose@v4.11.2/jws/compact/sign.ts:44:39)
    at SignJWT.sign (https://deno.land/x/jose@v4.11.2/jwt/sign.ts:132:16)
    at file:///[path-to-repo]/src/[some-file].ts:X:Y
```

The error was thrown by `jose` in a line like where `secret` was an environmental variable that was not set.

```js
const token = await new SignJWT(payload)
  // some settings
  .sign(secret);
```

The environmental variable was set on Deno Deploy, which is why it continued to work there.

Takeaway is fresh loses the stacktrace when throwing in an `await` statement.
