### ISSUE TITLE
Default demo app broken with error on `deno task start`

### ISSUE THREAD

**Issue by jimisaacs** [denoland/fresh#976]
The results of the following:
```sh
 ❯ deno run -A -r https://fresh.deno.dev my-project
```
```sh
 ❯ cd my-project
```
```sh
 ❯ deno task start                                                                                                       [22:32:43]
Task start deno run -A --watch=static/,routes/ dev.ts
Watcher Process started.
The manifest has been generated for 3 routes and 1 islands.
Listening on http://localhost:8000/
An error occurred during route handling or page rendering. Error: <Head> component is not supported in the browser, or during suspense renders.
    at Object.Head (https://deno.land/x/fresh@1.1.2/src/runtime/head.ts:15:11)
    at https://esm.sh/v102/preact-render-to-string@5.2.4/deno/preact-render-to-string.js:12:1626
    at E (https://esm.sh/v102/preact-render-to-string@5.2.4/deno/preact-render-to-string.js:12:1653)
    at E (https://esm.sh/v102/preact-render-to-string@5.2.4/deno/preact-render-to-string.js:12:918)
    at E (https://esm.sh/v102/preact-render-to-string@5.2.4/deno/preact-render-to-string.js:12:1729)
    at E (https://esm.sh/v102/preact-render-to-string@5.2.4/deno/preact-render-to-string.js:12:1729)
    at E (https://esm.sh/v102/preact-render-to-string@5.2.4/deno/preact-render-to-string.js:12:1729)
    at E (https://esm.sh/v102/preact-render-to-string@5.2.4/deno/preact-render-to-string.js:12:1729)
    at E (https://esm.sh/v102/preact-render-to-string@5.2.4/deno/preact-render-to-string.js:12:1729)
    at E (https://esm.sh/v102/preact-render-to-string@5.2.4/deno/preact-render-to-string.js:12:1729)
Caused by TypeError: Cannot read properties of undefined (reading 'context')
```

**Comment by jimisaacs** [comment]
```sh
 ❯ deno --version                                                                                                        [22:36:11]
deno 1.29.2 (release, aarch64-apple-darwin)
v8 10.9.194.5
typescript 4.9.4
```

**Comment by lino-levan** [comment]
Can confirm this is the case... a huge pain since it just brought down production. Looking into how to fix this. Will report what I found.

**Comment by jimisaacs** [comment]
Seems the issue is esm.sh, change to skypack fixed the example/demo:
```json
{
	"imports": {
		"@preact/signals-core": "https://cdn.skypack.dev/@preact/signals-core@1.0.1?dts",
		"@preact/signals": "https://cdn.skypack.dev/@preact/signals@1.0.3?dts",
		"$fresh/": "https://deno.land/x/fresh@1.1.2/",
		"asserts": "https://deno.land/std@0.168.0/testing/asserts.ts",
		"preact-render-to-string": "https://cdn.skypack.dev/preact-render-to-string@5.2.4?dts",
		"preact": "https://cdn.skypack.dev/preact@10.11.0?dts",
		"preact/debug": "https://cdn.skypack.dev/preact@10.11.0/debug?dts",
		"preact/hooks": "https://cdn.skypack.dev/preact@10.11.0/hooks?dts",
		"preact/jsx-runtime": "https://cdn.skypack.dev/preact@10.11.0/jsx-runtime?dts",
		"twind": "https://cdn.skypack.dev/twind@0.16.17?dts",
		"twind/sheets": "https://cdn.skypack.dev/twind@0.16.17/sheets?dts"
	}
}
```
It's possible this issue could/should expedite support for npm specifiers in the esbuild deno plugin.

**Comment by ieiekk** [comment]
I got the same error message on my Ventura 13.1 Intel iMac ,
but works fine on my Ventura 13.0.1 M1 max Macbook pro,
both test on the same command:

`deno run -A -r https://fresh.deno.dev my-project`
then
`deno task start`

**Comment by k41531** [comment]
I also faced the same error.
However, in my case, it worked normally on a local environment and the same error occurred when I did Deno Deploy.
The following issue #887 was similar, so I tried adding the following line to `import_map.json` and it worked fine even after Deno Deploy. I hope it will be helpful in some way.
```json
    "preact/hooks": "https://esm.sh/preact@10.11.0/hooks",
```

**Comment by lucacasonato** [comment]
Please try again (run `deno cache --reload main.ts` first). There was a bug in esm.sh that was causing this.

**Comment by jimisaacs** [comment]
Looks like it is resolved
